INSERT INTO items (name, damage, api_link, equipment_category, weight, cost)
VALUES
("Mason's tools", null, "/api/equipment/masons-tools", "Tools", 8, 10),
("Bottle, glass", null, "/api/equipment/bottle-glass", "Adventuring Gear", 2, 2),
("Blowgun needle", null, "/api/equipment/blowgun-needle", "Adventuring Gear", 1, 2),
("Mess Kit", null, "/api/equipment/mess-kit", "Adventuring Gear", 1, 2),
("Ink pen", null, "/api/equipment/ink-pen", "Adventuring Gear", 0, 2),
("Alchemist's supplies", null, "/api/equipment/alchemists-supplies", "Tools", 8, 50),
("Calligrapher's supplies", null, "/api/equipment/calligraphers-supplies", "Tools", 5, 10),
("Caltrops", null, "/api/equipment/caltrops", "Adventuring Gear", 2, 5),
("Bagpipes", null, "/api/equipment/bagpipes", "Tools", 6, 30),
("Jeweler's tools", null, "/api/equipment/jewelers-tools", "Tools", 2, 25),
("Jug or pitcher", null, "/api/equipment/jug-or-pitcher", "Adventuring Gear", 4, 2),
("Ball bearings (bag of 1,000)", null, "/api/equipment/ball-bearings-bag-of-1000", "Adventuring Gear", 2, 1),
("Burglar's Pack", null, "/api/equipment/burglars-pack", "Adventuring Gear", undefined, 16),
("Morningstar", '1d8', "/api/equipment/morningstar", "Weapon", 4, 15),
("Barding: Leather", null, "/api/equipment/barding-leather", "Mounts and Vehicles", 20, 40),
("Sling", '1d4', "/api/equipment/sling", "Weapon", 0, 1),
("Basket", null, "/api/equipment/basket", "Adventuring Gear", 2, 4),
("Breastplate", null, "/api/equipment/breastplate", "Armor", 20, 400),
("Horse, riding", null, "/api/equipment/horse-riding", "Mounts and Vehicles", undefined, 75),
("Carriage", null, "/api/equipment/carriage", "Mounts and Vehicles", 600, 100),
("Bedroll", null, "/api/equipment/bedroll", "Adventuring Gear", 7, 1),
("Bucket", null, "/api/equipment/bucket", "Adventuring Gear", 2, 5),
("Barrel", null, "/api/equipment/barrel", "Adventuring Gear", 70, 2),
("Barding: Hide", null, "/api/equipment/barding-hide", "Mounts and Vehicles", 24, 40),
("Bell", null, "/api/equipment/bell", "Adventuring Gear", 0, 1),
("Healer's Kit", null, "/api/equipment/healers-kit", "Adventuring Gear", 3, 5),
("Barding: Chain mail", null, "/api/equipment/barding-chain-mail", "Mounts and Vehicles", 110, 300),
("Barding: Studded Leather", null, "/api/equipment/barding-studded-leather", "Mounts and Vehicles", 26, 180),
("Barding: Half plate", null, "/api/equipment/barding-half-plate", "Mounts and Vehicles", 80, 3000),
("Lamp", null, "/api/equipment/lamp", "Adventuring Gear", 1, 5),
("Barding: Padded", null, "/api/equipment/barding-padded", "Mounts and Vehicles", 16, 20),
("Leather", null, "/api/equipment/leather", "Armor", 10, 10),
("Barding: Ring mail", null, "/api/equipment/barding-ring-mail", "Mounts and Vehicles", 80, 12),
("Hammer, sledge", null, "/api/equipment/hammer-sledge", "Adventuring Gear", 10, 2),
("Brewer's supplies", null, "/api/equipment/brewers-supplies", "Tools", 9, 20),
("Shovel", null, "/api/equipment/shovel", "Adventuring Gear", 5, 2),
("Battleaxe", '1d8', "/api/equipment/battleaxe", "Weapon", 4, 10),
("Ladder (10-foot)", null, "/api/equipment/ladder-10-foot", "Adventuring Gear", 25, 1),
("Barding: Plate", null, "/api/equipment/barding-plate", "Mounts and Vehicles", 130, 6000),
("Bit and bridle", null, "/api/equipment/bit-and-bridle", "Mounts and Vehicles", 1, 2),
("Ink (1 ounce bottle)", null, "/api/equipment/ink-1-ounce-bottle", "Adventuring Gear", 0, 10),
("Mule", null, "/api/equipment/mule", "Mounts and Vehicles", undefined, 8),
("Javelin", '1d6', "/api/equipment/javelin", "Weapon", 2, 5),
("Hide", null, "/api/equipment/hide", "Armor", 12, 10),
("Barding: Breastplate", null, "/api/equipment/barding-breastplate", "Mounts and Vehicles", 40, 1600),
("Blowgun", "1d1", "/api/equipment/blowgun", "Weapon", 1, 10),
("Horse, draft", null, "/api/equipment/horse-draft", "Mounts and Vehicles", undefined, 50),
("Acid (vial)", null, "/api/equipment/acid-vial", "Adventuring Gear", 1, 25),
("Hunting trap", null, "/api/equipment/hunting-trap", "Adventuring Gear", 25, 5),
("Lantern, bullseye", null, "/api/equipment/lantern-bullseye", "Adventuring Gear", 2, 10),
("Greatclub", "1d8", "/api/equipment/greatclub", "Weapon", 10, 2),
("Mastiff", null, "/api/equipment/mastiff", "Mounts and Vehicles", undefined, 25),
("Hammer", null, "/api/equipment/hammer", "Adventuring Gear", 3, 1),
("Blanket", null, "/api/equipment/blanket", "Adventuring Gear", 3, 5),
("Book", null, "/api/equipment/book", "Adventuring Gear", 5, 25),
("Block and tackle", null, "/api/equipment/block-and-tackle", "Adventuring Gear", 5, 1),
("Barding: Splint", null, "/api/equipment/barding-splint", "Mounts and Vehicles", 120, 800),
("Disguise Kit", null, "/api/equipment/disguise-kit", "Adventuring Gear", 3, 25),
("Cartographer's tools", null, "/api/equipment/cartographers-tools", "Tools", 6, 15),
("Sling bullet", null, "/api/equipment/sling-bullet", "Adventuring Gear", 1.5, 1),
("Entertainer's Pack", null, "/api/equipment/entertainers-pack", "Adventuring Gear", undefined, 40),
("Sled", null, "/api/equipment/sled", "Mounts and Vehicles", 300, 20),
("Emblem", null, "/api/equipment/emblem", "Adventuring Gear", 0, 5),
("Cart", null, "/api/equipment/cart", "Mounts and Vehicles", 200, 15),
("Fishing tackle", null, "/api/equipment/fishing-tackle", "Adventuring Gear", 4, 1),
("Soap", null, "/api/equipment/soap", "Adventuring Gear", 0, 2),
("Camel", null, "/api/equipment/camel", "Mounts and Vehicles", undefined, 50),
("Case, map or scroll", null, "/api/equipment/case-map-or-scroll", "Adventuring Gear", 1, 1),
("Animal Feed (1 day)", null, "/api/equipment/animal-feed-1-day", "Mounts and Vehicles", 10, 5),
("Antitoxin (vial)", null, "/api/equipment/antitoxin-vial", "Adventuring Gear", 0, 50),
("Abacus", null, "/api/equipment/abacus", "Adventuring Gear", 2, 2),
("Staff", null, "/api/equipment/staff", "Adventuring Gear", 4, 5),
("Spyglass", null, "/api/equipment/spyglass", "Adventuring Gear", 1, 1000),
("Spear", "1d4", "/api/equipment/spear", "Weapon", 3, 1),
("Dungeoneer's Pack", null, "/api/equipment/dungeoneers-pack", "Adventuring Gear", undefined, 12),
("Woodcarver's tools", null, "/api/equipment/woodcarvers-tools", "Tools", 5, 1),
("Wagon", null, "/api/equipment/wagon", "Mounts and Vehicles", 400, 35),
("Tinderbox", null, "/api/equipment/tinderbox", "Adventuring Gear", 1, 5),
("Sprig of mistletoe", null, "/api/equipment/sprig-of-mistletoe", "Adventuring Gear", 0, 1),
("Totem", null, "/api/equipment/totem", "Adventuring Gear", 0, 1),
("Spellbook", null, "/api/equipment/spellbook", "Adventuring Gear", 3, 50),
("Vial", null, "/api/equipment/vial", "Adventuring Gear", 0, 1),
("Alchemist's fire (flask)", null, "/api/equipment/alchemists-fire-flask", "Adventuring Gear", 1, 50),
("Carpenter's tools", null, "/api/equipment/carpenters-tools", "Tools", 6, 8),
("Saddle, Exotic", null, "/api/equipment/saddle-exotic", "Mounts and Vehicles", 50, 60),
("Mirror, steel", null, "/api/equipment/mirror-steel", "Adventuring Gear", 0.5, 5),
("Backpack", null, "/api/equipment/backpack", "Adventuring Gear", 5, 2),
("Maul", "2d6", "/api/equipment/maul", "Weapon", 10, 10),
("Navigator's tools", null, "/api/equipment/navigators-tools", "Tools", 2, 25),
("Arrow", null, "/api/equipment/arrow", "Adventuring Gear", 1, 5),
("Leatherworker's tools", null, "/api/equipment/leatherworkers-tools", "Tools", 5, 5),
("Potter's tools", null, "/api/equipment/potters-tools", "Tools", 3, 10),
("Lantern, hooded", null, "/api/equipment/lantern-hooded", "Adventuring Gear", 2, 5),
("Manacles", null, "/api/equipment/manacles", "Adventuring Gear", 6, 2),
("Magnifying glass", null, "/api/equipment/magnifying-glass", "Adventuring Gear", 0, 100),
("Lock", null, "/api/equipment/lock", "Adventuring Gear", 1, 10),
("Light hammer", "1d4", "/api/equipment/light-hammer", "Weapon", 2, 2),
("Scimitar", "1d6", "/api/equipment/scimitar", "Weapon", 3, 25),
("Longsword", "1d8", "/api/equipment/longsword", "Weapon", 3, 15),
("Longbow", "1d8", "/api/equipment/longbow", "Weapon", 2, 50),
("Longbow", "1d8", "/api/equipment/longbow", "Weapon", 2, 50),
("Sickle", "1d4", "/api/equipment/sickle", "Weapon", 2, 1),
("Pan flute", null, "/api/equipment/pan-flute", "Tools", 2, 12),
("Whetstone", null, "/api/equipment/whetstone", "Adventuring Gear", 1, 1),
("Waterskin", null, "/api/equipment/waterskin", "Adventuring Gear", 5, 2),
("Warhorse", null, "/api/equipment/warhorse", "Mounts and Vehicles", undefined, 400),
("Wooden staff", null, "/api/equipment/wooden-staff", "Adventuring Gear", 4, 5),
("Padded", null, "/api/equipment/padded", "Armor", 8, 5),
("Horn", null, "/api/equipment/horn", "Tools", 2, 3),
("Holy water (flask)", null, "/api/equipment/holy-water-flask", "Adventuring Gear", 1, 25),
("Warship", null, "/api/equipment/warship", "Mounts and Vehicles", undefined, 25000),
("Whip", "1d4", "/api/equipment/whip", "Weapon", 3, 2),
("Stabling (1 day)", null, "/api/equipment/stabling-1-day", "Mounts and Vehicles", 0, 5),
("Viol", null, "/api/equipment/viol", "Tools", 1, 30),
("Wand", null, "/api/equipment/wand", "Adventuring Gear", 1, 10),
("Torch", null, "/api/equipment/torch", "Adventuring Gear", 1, 1),
("Thieves' tools", null, "/api/equipment/thieves-tools", "Tools", 1, 25),
("Oil (flask)", null, "/api/equipment/oil-flask", "Adventuring Gear", 1, 1),
("Hourglass", null, "/api/equipment/hourglass", "Adventuring Gear", 1, 25),
("Orb", null, "/api/equipment/orb", "Adventuring Gear", 3, 20),
("Dulcimer", null, "/api/equipment/dulcimer", "Tools", 10, 25),
("Painter's supplies", null, "/api/equipment/painters-supplies", "Tools", 5, 10),
("Pick, miner's", null, "/api/equipment/pick-miners", "Adventuring Gear", 10, 2),
("Rations (1 day)", null, "/api/equipment/rations-1-day", "Adventuring Gear", 2, 5),
("Net", "1d0", "/api/equipment/net", "Weapon", 3, 1),
("Weaver's tools", null, "/api/equipment/weavers-tools", "Tools", 5, 1),
("Tent, two-person", null, "/api/equipment/tent-two-person", "Adventuring Gear", 20, 2),
("Studded Leather", null, "/api/equipment/studded-leather", "Armor", 13, 45),
("Shortbow", "1d6", "/api/equipment/shortbow", "Weapon", 2, 25),
("Signet ring", null, "/api/equipment/signet-ring", "Adventuring Gear", 0, 5),
("Mace", "1d6", "/api/equipment/mace", "Weapon", 4, 5),
("Sealing wax", null, "/api/equipment/sealing-wax", "Adventuring Gear", 0, 5),
("Rapier", "1d8", "/api/equipment/rapier", "Weapon", 2, 25),
("Perfume (vial)", null, "/api/equipment/perfume-vial", "Adventuring Gear", 0, 5),
("Pot, iron", null, "/api/equipment/pot-iron", "Adventuring Gear", 10, 2),
("Handaxe", "1d6", "/api/equipment/handaxe", "Weapon", 2, 5),
("Keelboat", null, "/api/equipment/keelboat", "Mounts and Vehicles", undefined, 3000),
("Candle", null, "/api/equipment/candle", "Adventuring Gear", 0, 1),
("Amulet", null, "/api/equipment/amulet", "Adventuring Gear", 1, 5),
("Saddle, Pack", null, "/api/equipment/saddle-pack", "Mounts and Vehicles", 15, 5),
("Crossbow bolt", null, "/api/equipment/crossbow-bolt", "Adventuring Gear", 1.5, 5),
("Rod", null, "/api/equipment/rod", "Adventuring Gear", 2, 10),
("Piton", null, "/api/equipment/piton", "Adventuring Gear", 0.25, 5),
("Parchment (one sheet)", null, "/api/equipment/parchment-one-sheet", "Adventuring Gear", 0, 1),
("Longship", null, "/api/equipment/longship", "Mounts and Vehicles", undefined, 10000),
("Riding", null, "/api/equipment/riding", "Mounts and Vehicles", 25, 10),
("Plate", null, "/api/equipment/plate", "Armor", 65, 1500),
("Priest's Pack", null, "/api/equipment/priests-pack", "Adventuring Gear", undefined, 19),
("Halberd", "1d10", "/api/equipment/halberd", "Weapon", 6, 20),
("Playing card set", null, "/api/equipment/playing-card-set", "Tools", 0, 5),
("Ram, portable", null, "/api/equipment/ram-portable", "Adventuring Gear", 35, 4),
("Paper (one sheet)", null, "/api/equipment/paper-one-sheet", "Adventuring Gear", 0, 2),
("Barding: Scale mail", null, "/api/equipment/barding-scale-mail", "Mounts and Vehicles", 90, 200),
("Scale, merchant's", null, "/api/equipment/scale-merchants", "Adventuring Gear", 3, 5),
("Shield", null, "/api/equipment/shield", "Armor", 6, 10),
("Saddlebags", null, "/api/equipment/saddlebags", "Mounts and Vehicles", 8, 4),
("Sack", null, "/api/equipment/sack", "Adventuring Gear", 0.5, 1),
("Quiver", null, "/api/equipment/quiver", "Adventuring Gear", 1, 1),
("Chain (10 feet)", null, "/api/equipment/chain-10-feet", "Adventuring Gear", 10, 5),
("Signal whistle", null, "/api/equipment/signal-whistle", "Adventuring Gear", 0, 5),
("Rope, silk (50 feet)", null, "/api/equipment/rope-silk-50-feet", "Adventuring Gear", 5, 10),
("Quarterstaff", "1d6", "/api/equipment/quarterstaff", "Weapon", 4, 2),
("Pouch", null, "/api/equipment/pouch", "Adventuring Gear", 1, 5),
("Shawm", null, "/api/equipment/shawm", "Tools", 1, 2),
("Ring Mail", null, "/api/equipment/ring-mail", "Armor", 40, 30),
("Scale Mail", null, "/api/equipment/scale-mail", "Armor", 45, 50),
("Scholar's Pack", null, "/api/equipment/scholars-pack", "Adventuring Gear", undefined, 40),
("Rowboat", null, "/api/equipment/rowboat", "Mounts and Vehicles", undefined, 50),
("War pick", "1d8", "/api/equipment/war-pick", "Weapon", 2, 5),
("Splint", null, "/api/equipment/splint", "Armor", 60, 200),
("Spike, iron", null, "/api/equipment/spike-iron", "Adventuring Gear", 5, 1),
("Barding: Chain shirt", null, "/api/equipment/barding-chain-shirt", "Mounts and Vehicles", 40, 200),
("Trident", "1d6", "/api/equipment/trident", "Weapon", 4, 5),
("Tinker's tools", null, "/api/equipment/tinkers-tools", "Tools", 10, 50),
("Yew wand", null, "/api/equipment/yew-wand", "Adventuring Gear", 1, 10),
("Smith's tools", null, "/api/equipment/smiths-tools", "Tools", 8, 20),
("Saddle, Military", null, "/api/equipment/saddle-military", "Mounts and Vehicles", 30, 20),
("Cobbler's tools", null, "/api/equipment/cobblers-tools", "Tools", 5, 5),
("Shortsword", "1d6", "/api/equipment/shortsword", "Weapon", 2, 10),
("Climber's Kit", null, "/api/equipment/climbers-kit", "Adventuring Gear", 12, 25),
("Potion of healing", null, "/api/equipment/potion-of-healing", "Adventuring Gear", 0.5, 50),
("Poison, basic (vial)", null, "/api/equipment/poison-basic-vial", "Adventuring Gear", 0, 100),
("Case, crossbow bolt", null, "/api/equipment/case-crossbow-bolt", "Adventuring Gear", 1, 1),
("Pony", null, "/api/equipment/pony", "Mounts and Vehicles", undefined, 30),
("Sailing ship", null, "/api/equipment/sailing-ship", "Mounts and Vehicles", undefined, 10000),
("Pike", "1d10", "/api/equipment/pike", "Weapon", 18, 5),
("Chalk (1 piece)", null, "/api/equipment/chalk-1-piece", "Adventuring Gear", 0, 1),
("Reliquary", null, "/api/equipment/reliquary", "Adventuring Gear", 2, 5),
("Herbalism Kit", null, "/api/equipment/herbalism-kit", "Adventuring Gear", 3, 5),
("Club", "1d4", "/api/equipment/club", "Weapon", 2, 1),
("Lute", null, "/api/equipment/lute", "Tools", 2, 35),
("Warhammer", "1d8", "/api/equipment/warhammer", "Weapon", 2, 15),
("Lance", "1d12", "/api/equipment/lance", "Weapon", 6, 10),
("Donkey", null, "/api/equipment/donkey", "Mounts and Vehicles", undefined, 8),
("Flask or tankard", null, "/api/equipment/flask-or-tankard", "Adventuring Gear", 1, 2),
("Clothes, common", null, "/api/equipment/clothes-common", "Adventuring Gear", 3, 5),
("Galley", null, "/api/equipment/galley", "Mounts and Vehicles", undefined, 30000),
("Glaive", "1d10", "/api/equipment/glaive", "Weapon", 6, 20),
("Glassblower's tools", null, "/api/equipment/glassblowers-tools", "Tools", 5, 30),
("Elephant", null, "/api/equipment/elephant", "Mounts and Vehicles", undefined, 200),
("Flail", "1d8", "/api/equipment/flail", "Weapon", 2, 10),
("Lyre", null, "/api/equipment/lyre", "Tools", 2, 30),
("Forgery Kit", null, "/api/equipment/forgery-kit", "Adventuring Gear", 5, 15),
("Half Plate", null, "/api/equipment/half-plate", "Armor", 40, 750),
("Greatsword", "2d6", "/api/equipment/greatsword", "Weapon", 6, 50),
("Clothes, traveler's", null, "/api/equipment/clothes-travelers", "Adventuring Gear", 4, 2),
("Chain Shirt", null, "/api/equipment/chain-shirt", "Armor", 20, 50),
("Flute", null, "/api/equipment/flute", "Tools", 1, 2),
("Chain Mail", null, "/api/equipment/chain-mail", "Armor", 55, 75),
("Chest", null, "/api/equipment/chest", "Adventuring Gear", 25, 5),
("Clothes, costume", null, "/api/equipment/clothes-costume", "Adventuring Gear", 4, 5),
("Clothes, fine", null, "/api/equipment/clothes-fine", "Adventuring Gear", 6, 15),
("Drum", null, "/api/equipment/drum", "Tools", 3, 6),
("Explorer's Pack", null, "/api/equipment/explorers-pack", "Adventuring Gear", undefined, 10),
("Greataxe", "1d12", "/api/equipment/greataxe", "Weapon", 7, 30),
("Component pouch", null, "/api/equipment/component-pouch", "Adventuring Gear", 2, 25),
("Grappling hook", null, "/api/equipment/grappling-hook", "Adventuring Gear", 4, 2),
("Crossbow, heavy", "1d10", "/api/equipment/crossbow-heavy", "Weapon", 18, 50),
("Robes", null, "/api/equipment/robes", "Adventuring Gear", 4, 1),
("Crossbow, hand", "1d6", "/api/equipment/crossbow-hand", "Weapon", 3, 75),
("Cook's utensils", null, "/api/equipment/cooks-utensils", "Tools", 8, 1),
("Chariot", null, "/api/equipment/chariot", "Mounts and Vehicles", 100, 250),
("Dagger", "1d4", "/api/equipment/dagger", "Weapon", 1, 2),
("Poisoner's Kit", null, "/api/equipment/poisoners-kit", "Adventuring Gear", 2, 50),
("Rope, hempen (50 feet)", null, "/api/equipment/rope-hempen-50-feet", "Adventuring Gear", 10, 1),
("Pole (10-foot)", null, "/api/equipment/pole-10-foot", "Adventuring Gear", 7, 5),
("Crowbar", null, "/api/equipment/crowbar", "Adventuring Gear", 5, 2),
("Dice set", null, "/api/equipment/dice-set", "Tools", 0, 1),
("Dart", "1d4", "/api/equipment/dart", "Weapon", 0.25, 5),
("Crossbow, light", "1d8", "/api/equipment/crossbow-light", "Weapon", 5, 25),
("Crystal", null, "/api/equipment/crystal", "Adventuring Gear", 1, 10),
("Diplomat's Pack", null, "/api/equipment/diplomats-pack", "Adventuring Gear", undefined, 39),
