INSERT INTO items (name, damage_dice, api_link, equipment_category, weight, cost)
VALUES
('Splint', null, '/api/equipment/splint', 'Armor', 60, 200),
('Spike, iron', null, '/api/equipment/spike-iron', 'Adventuring Gear', 5, 1),
('Signet ring', null, '/api/equipment/signet-ring', 'Adventuring Gear', 0, 5),
('Saddle, Military', null, '/api/equipment/saddle-military', 'Mounts and Vehicles', 30, 20),
('Galley', null, '/api/equipment/galley', 'Mounts and Vehicles', null, 30000),
('Chalk (1 piece)', null, '/api/equipment/chalk-1-piece', 'Adventuring Gear', 0, 1),
('Glaive', '1d10', '/api/equipment/glaive', 'Weapon', 6, 20),
('Crossbow, hand', '1d6', '/api/equipment/crossbow-hand', 'Weapon', 3, 75),
('Manacles', null, '/api/equipment/manacles', 'Adventuring Gear', 6, 2),
('Net', '1d0', '/api/equipment/net', 'Weapon', 3, 1),
('Carpenter''s tools', null, '/api/equipment/carpenters-tools', 'Tools', 6, 8),
('Blowgun needle', null, '/api/equipment/blowgun-needle', 'Adventuring Gear', 1, 2),
('Mason''s tools', null, '/api/equipment/masons-tools', 'Tools', 8, 10),
('Brewer''s supplies', null, '/api/equipment/brewers-supplies', 'Tools', 9, 20),
('Lance', '1d12', '/api/equipment/lance', 'Weapon', 6, 10),
('Candle', null, '/api/equipment/candle', 'Adventuring Gear', 0, 1),
('Book', null, '/api/equipment/book', 'Adventuring Gear', 5, 25),
('Lyre', null, '/api/equipment/lyre', 'Tools', 2, 30),
('Grappling hook', null, '/api/equipment/grappling-hook', 'Adventuring Gear', 4, 2),
('Longship', null, '/api/equipment/longship', 'Mounts and Vehicles', null, 10000),
('Abacus', null, '/api/equipment/abacus', 'Adventuring Gear', 2, 2),
('Barding: Padded', null, '/api/equipment/barding-padded', 'Mounts and Vehicles', 16, 20),
('Lute', null, '/api/equipment/lute', 'Tools', 2, 35),
('Barding: Breastplate', null, '/api/equipment/barding-breastplate', 'Mounts and Vehicles', 40, 1600),
('Hourglass', null, '/api/equipment/hourglass', 'Adventuring Gear', 1, 25),
('Ball bearings (bag of 1,000)', null, '/api/equipment/ball-bearings-bag-of-1000', 'Adventuring Gear', 2, 1),
('Leatherworker''s tools', null, '/api/equipment/leatherworkers-tools', 'Tools', 5, 5),
('Sickle', '1d4', '/api/equipment/sickle', 'Weapon', 2, 1),
('Orb', null, '/api/equipment/orb', 'Adventuring Gear', 3, 20),
('Signal whistle', null, '/api/equipment/signal-whistle', 'Adventuring Gear', 0, 5),
('Maul', '2d6', '/api/equipment/maul', 'Weapon', 10, 10),
('Light hammer', '1d4', '/api/equipment/light-hammer', 'Weapon', 2, 2),
('Component pouch', null, '/api/equipment/component-pouch', 'Adventuring Gear', 2, 25),
('War pick', '1d8', '/api/equipment/war-pick', 'Weapon', 2, 5),
('Wagon', null, '/api/equipment/wagon', 'Mounts and Vehicles', 400, 35),
('Sled', null, '/api/equipment/sled', 'Mounts and Vehicles', 300, 20),
('Clothes, fine', null, '/api/equipment/clothes-fine', 'Adventuring Gear', 6, 15),
('Scholar''s Pack', null, '/api/equipment/scholars-pack', 'Adventuring Gear', null, 40),
('Shield', null, '/api/equipment/shield', 'Armor', 6, 10),
('Sealing wax', null, '/api/equipment/sealing-wax', 'Adventuring Gear', 0, 5),
('Sling bullet', null, '/api/equipment/sling-bullet', 'Adventuring Gear', 1.5, 1),
('Whetstone', null, '/api/equipment/whetstone', 'Adventuring Gear', 1, 1),
('Cobbler''s tools', null, '/api/equipment/cobblers-tools', 'Tools', 5, 5),
('Scimitar', '1d6', '/api/equipment/scimitar', 'Weapon', 3, 25),
('Clothes, traveler''s', null, '/api/equipment/clothes-travelers', 'Adventuring Gear', 4, 2),
('Cook''s utensils', null, '/api/equipment/cooks-utensils', 'Tools', 8, 1),
('Chain Shirt', null, '/api/equipment/chain-shirt', 'Armor', 20, 50),
('Totem', null, '/api/equipment/totem', 'Adventuring Gear', 0, 1),
('Barding: Scale mail', null, '/api/equipment/barding-scale-mail', 'Mounts and Vehicles', 90, 200),
('Backpack', null, '/api/equipment/backpack', 'Adventuring Gear', 5, 2),
('Barding: Chain shirt', null, '/api/equipment/barding-chain-shirt', 'Mounts and Vehicles', 40, 200),
('Blowgun', '1d1', '/api/equipment/blowgun', 'Weapon', 1, 10),
('Bagpipes', null, '/api/equipment/bagpipes', 'Tools', 6, 30),
('Acid (vial)', null, '/api/equipment/acid-vial', 'Adventuring Gear', 1, 25),
('Animal Feed (1 day)', null, '/api/equipment/animal-feed-1-day', 'Mounts and Vehicles', 10, 5),
('Alchemist''s supplies', null, '/api/equipment/alchemists-supplies', 'Tools', 8, 50),
('Alchemist''s fire (flask)', null, '/api/equipment/alchemists-fire-flask', 'Adventuring Gear', 1, 50),
('Barding: Ring mail', null, '/api/equipment/barding-ring-mail', 'Mounts and Vehicles', 80, 12),
('Camel', null, '/api/equipment/camel', 'Mounts and Vehicles', null, 50),
('Blanket', null, '/api/equipment/blanket', 'Adventuring Gear', 3, 5),
('Barrel', null, '/api/equipment/barrel', 'Adventuring Gear', 70, 2),
('Barding: Studded Leather', null, '/api/equipment/barding-studded-leather', 'Mounts and Vehicles', 26, 180),
('Arrow', null, '/api/equipment/arrow', 'Adventuring Gear', 1, 5),
('Basket', null, '/api/equipment/basket', 'Adventuring Gear', 2, 4),
('Barding: Plate', null, '/api/equipment/barding-plate', 'Mounts and Vehicles', 130, 6000),
('Burglar''s Pack', null, '/api/equipment/burglars-pack', 'Adventuring Gear', null, 16),
('Block and tackle', null, '/api/equipment/block-and-tackle', 'Adventuring Gear', 5, 1),
('Bucket', null, '/api/equipment/bucket', 'Adventuring Gear', 2, 5),
('Crossbow bolt', null, '/api/equipment/crossbow-bolt', 'Adventuring Gear', 1.5, 5),
('Carriage', null, '/api/equipment/carriage', 'Mounts and Vehicles', 600, 100),
('Caltrops', null, '/api/equipment/caltrops', 'Adventuring Gear', 2, 5),
('Disguise Kit', null, '/api/equipment/disguise-kit', 'Adventuring Gear', 3, 25),
('Clothes, common', null, '/api/equipment/clothes-common', 'Adventuring Gear', 3, 5),
('Breastplate', null, '/api/equipment/breastplate', 'Armor', 20, 400),
('Clothes, costume', null, '/api/equipment/clothes-costume', 'Adventuring Gear', 4, 5),
('Dart', '1d4', '/api/equipment/dart', 'Weapon', 0.25, 5),
('Dagger', '1d4', '/api/equipment/dagger', 'Weapon', 1, 2),
('Calligrapher''s supplies', null, '/api/equipment/calligraphers-supplies', 'Tools', 5, 10),
('Case, map or scroll', null, '/api/equipment/case-map-or-scroll', 'Adventuring Gear', 1, 1),
('Bedroll', null, '/api/equipment/bedroll', 'Adventuring Gear', 7, 1),
('Barding: Splint', null, '/api/equipment/barding-splint', 'Mounts and Vehicles', 120, 800),
('Bit and bridle', null, '/api/equipment/bit-and-bridle', 'Mounts and Vehicles', 1, 2),
('Chain Mail', null, '/api/equipment/chain-mail', 'Armor', 55, 75),
('Case, crossbow bolt', null, '/api/equipment/case-crossbow-bolt', 'Adventuring Gear', 1, 1),
('Chariot', null, '/api/equipment/chariot', 'Mounts and Vehicles', 100, 250),
('Climber''s Kit', null, '/api/equipment/climbers-kit', 'Adventuring Gear', 12, 25),
('Chest', null, '/api/equipment/chest', 'Adventuring Gear', 25, 5),
('Chain (10 feet)', null, '/api/equipment/chain-10-feet', 'Adventuring Gear', 10, 5),
('Bottle, glass', null, '/api/equipment/bottle-glass', 'Adventuring Gear', 2, 2),
('Bell', null, '/api/equipment/bell', 'Adventuring Gear', 0, 1),
('Cart', null, '/api/equipment/cart', 'Mounts and Vehicles', 200, 15),
('Cartographer''s tools', null, '/api/equipment/cartographers-tools', 'Tools', 6, 15),
('Flail', '1d8', '/api/equipment/flail', 'Weapon', 2, 10),
('Barding: Chain mail', null, '/api/equipment/barding-chain-mail', 'Mounts and Vehicles', 110, 300),
('Ink pen', null, '/api/equipment/ink-pen', 'Adventuring Gear', 0, 2),
('Hammer', null, '/api/equipment/hammer', 'Adventuring Gear', 3, 1),
('Greataxe', '1d12', '/api/equipment/greataxe', 'Weapon', 7, 30),
('Hammer, sledge', null, '/api/equipment/hammer-sledge', 'Adventuring Gear', 10, 2),
('Battleaxe', '1d8', '/api/equipment/battleaxe', 'Weapon', 4, 10),
('Flask or tankard', null, '/api/equipment/flask-or-tankard', 'Adventuring Gear', 1, 2),
('Club', '1d4', '/api/equipment/club', 'Weapon', 2, 1),
('Half Plate', null, '/api/equipment/half-plate', 'Armor', 40, 750),
('Healer''s Kit', null, '/api/equipment/healers-kit', 'Adventuring Gear', 3, 5),
('Lamp', null, '/api/equipment/lamp', 'Adventuring Gear', 1, 5),
('Longbow', '1d8', '/api/equipment/longbow', 'Weapon', 2, 50),
('Horse, draft', null, '/api/equipment/horse-draft', 'Mounts and Vehicles', null, 50),
('Explorer''s Pack', null, '/api/equipment/explorers-pack', 'Adventuring Gear', null, 10),
('Jug or pitcher', null, '/api/equipment/jug-or-pitcher', 'Adventuring Gear', 4, 2),
('Greatsword', '2d6', '/api/equipment/greatsword', 'Weapon', 6, 50),
('Hide', null, '/api/equipment/hide', 'Armor', 12, 10),
('Ink (1 ounce bottle)', null, '/api/equipment/ink-1-ounce-bottle', 'Adventuring Gear', 0, 10),
('Herbalism Kit', null, '/api/equipment/herbalism-kit', 'Adventuring Gear', 3, 5),
('Leather', null, '/api/equipment/leather', 'Armor', 10, 10),
('Mess Kit', null, '/api/equipment/mess-kit', 'Adventuring Gear', 1, 2),
('Horn', null, '/api/equipment/horn', 'Tools', 2, 3),
('Lantern, bullseye', null, '/api/equipment/lantern-bullseye', 'Adventuring Gear', 2, 10),
('Lock', null, '/api/equipment/lock', 'Adventuring Gear', 1, 10),
('Barding: Leather', null, '/api/equipment/barding-leather', 'Mounts and Vehicles', 20, 40),
('Rod', null, '/api/equipment/rod', 'Adventuring Gear', 2, 10),
('Magnifying glass', null, '/api/equipment/magnifying-glass', 'Adventuring Gear', 0, 100),
('Horse, riding', null, '/api/equipment/horse-riding', 'Mounts and Vehicles', null, 75),
('Mastiff', null, '/api/equipment/mastiff', 'Mounts and Vehicles', null, 25),
('Plate', null, '/api/equipment/plate', 'Armor', 65, 1500),
('Yew wand', null, '/api/equipment/yew-wand', 'Adventuring Gear', 1, 10),
('Soap', null, '/api/equipment/soap', 'Adventuring Gear', 0, 2),
('Warship', null, '/api/equipment/warship', 'Mounts and Vehicles', null, 25000),
('Sprig of mistletoe', null, '/api/equipment/sprig-of-mistletoe', 'Adventuring Gear', 0, 1),
('Pike', '1d10', '/api/equipment/pike', 'Weapon', 18, 5),
('Warhorse', null, '/api/equipment/warhorse', 'Mounts and Vehicles', null, 400),
('Whip', '1d4', '/api/equipment/whip', 'Weapon', 3, 2),
('Quarterstaff', '1d6', '/api/equipment/quarterstaff', 'Weapon', 4, 2),
('Scale Mail', null, '/api/equipment/scale-mail', 'Armor', 45, 50),
('Piton', null, '/api/equipment/piton', 'Adventuring Gear', 0.25, 5),
('Ring Mail', null, '/api/equipment/ring-mail', 'Armor', 40, 30),
('Rope, silk (50 feet)', null, '/api/equipment/rope-silk-50-feet', 'Adventuring Gear', 5, 10),
('Rope, hempen (50 feet)', null, '/api/equipment/rope-hempen-50-feet', 'Adventuring Gear', 10, 1),
('Weaver''s tools', null, '/api/equipment/weavers-tools', 'Tools', 5, 1),
('Poisoner''s Kit', null, '/api/equipment/poisoners-kit', 'Adventuring Gear', 2, 50),
('Spellbook', null, '/api/equipment/spellbook', 'Adventuring Gear', 3, 50),
('Sack', null, '/api/equipment/sack', 'Adventuring Gear', 0.5, 1),
('Mirror, steel', null, '/api/equipment/mirror-steel', 'Adventuring Gear', 0.5, 5),
('Mace', '1d6', '/api/equipment/mace', 'Weapon', 4, 5),
('Sailing ship', null, '/api/equipment/sailing-ship', 'Mounts and Vehicles', null, 10000),
('Shortbow', '1d6', '/api/equipment/shortbow', 'Weapon', 2, 25),
('Shovel', null, '/api/equipment/shovel', 'Adventuring Gear', 5, 2),
('Barding: Half plate', null, '/api/equipment/barding-half-plate', 'Mounts and Vehicles', 80, 3000),
('Scale, merchant''s', null, '/api/equipment/scale-merchants', 'Adventuring Gear', 3, 5),
('Shortsword', '1d6', '/api/equipment/shortsword', 'Weapon', 2, 10),
('Riding', null, '/api/equipment/riding', 'Mounts and Vehicles', 25, 10),
('Rowboat', null, '/api/equipment/rowboat', 'Mounts and Vehicles', null, 50),
('Barding: Hide', null, '/api/equipment/barding-hide', 'Mounts and Vehicles', 24, 40),
('Shawm', null, '/api/equipment/shawm', 'Tools', 1, 2),
('Holy water (flask)', null, '/api/equipment/holy-water-flask', 'Adventuring Gear', 1, 25),
('Ladder (10-foot)', null, '/api/equipment/ladder-10-foot', 'Adventuring Gear', 25, 1),
('Vial', null, '/api/equipment/vial', 'Adventuring Gear', 0, 1),
('Trident', '1d6', '/api/equipment/trident', 'Weapon', 4, 5),
('Hunting trap', null, '/api/equipment/hunting-trap', 'Adventuring Gear', 25, 5),
('Greatclub', '1d8', '/api/equipment/greatclub', 'Weapon', 10, 2),
('Lantern, hooded', null, '/api/equipment/lantern-hooded', 'Adventuring Gear', 2, 5),
('Viol', null, '/api/equipment/viol', 'Tools', 1, 30),
('Jeweler''s tools', null, '/api/equipment/jewelers-tools', 'Tools', 2, 25),
('Halberd', '1d10', '/api/equipment/halberd', 'Weapon', 6, 20),
('Crowbar', null, '/api/equipment/crowbar', 'Adventuring Gear', 5, 2),
('Handaxe', '1d6', '/api/equipment/handaxe', 'Weapon', 2, 5),
('Forgery Kit', null, '/api/equipment/forgery-kit', 'Adventuring Gear', 5, 15),
('Crossbow, heavy', '1d10', '/api/equipment/crossbow-heavy', 'Weapon', 18, 50),
('Priest''s Pack', null, '/api/equipment/priests-pack', 'Adventuring Gear', null, 19),
('Pot, iron', null, '/api/equipment/pot-iron', 'Adventuring Gear', 10, 2),
('Diplomat''s Pack', null, '/api/equipment/diplomats-pack', 'Adventuring Gear', null, 39),
('Oil (flask)', null, '/api/equipment/oil-flask', 'Adventuring Gear', 1, 1),
('Morningstar', '1d8', '/api/equipment/morningstar', 'Weapon', 4, 15),
('Rapier', '1d8', '/api/equipment/rapier', 'Weapon', 2, 25),
('Crossbow, light', '1d8', '/api/equipment/crossbow-light', 'Weapon', 5, 25),
('Entertainer''s Pack', null, '/api/equipment/entertainers-pack', 'Adventuring Gear', null, 40),
('Drum', null, '/api/equipment/drum', 'Tools', 3, 6),
('Crystal', null, '/api/equipment/crystal', 'Adventuring Gear', 1, 10),
('Spear', '1d4', '/api/equipment/spear', 'Weapon', 3, 1),
('Dice set', null, '/api/equipment/dice-set', 'Tools', 0, 1),
('Pole (10-foot)', null, '/api/equipment/pole-10-foot', 'Adventuring Gear', 7, 5),
('Potter''s tools', null, '/api/equipment/potters-tools', 'Tools', 3, 10),
('Perfume (vial)', null, '/api/equipment/perfume-vial', 'Adventuring Gear', 0, 5),
('Emblem', null, '/api/equipment/emblem', 'Adventuring Gear', 0, 5),
('Javelin', '1d6', '/api/equipment/javelin', 'Weapon', 2, 5),
('Flute', null, '/api/equipment/flute', 'Tools', 1, 2),
('Elephant', null, '/api/equipment/elephant', 'Mounts and Vehicles', null, 200),
('Saddle, Exotic', null, '/api/equipment/saddle-exotic', 'Mounts and Vehicles', 50, 60),
('Pan flute', null, '/api/equipment/pan-flute', 'Tools', 2, 12),
('Painter''s supplies', null, '/api/equipment/painters-supplies', 'Tools', 5, 10),
('Potion of healing', null, '/api/equipment/potion-of-healing', 'Adventuring Gear', 0.5, 50),
('Pony', null, '/api/equipment/pony', 'Mounts and Vehicles', null, 30),
('Robes', null, '/api/equipment/robes', 'Adventuring Gear', 4, 1),
('Rations (1 day)', null, '/api/equipment/rations-1-day', 'Adventuring Gear', 2, 5),
('Parchment (one sheet)', null, '/api/equipment/parchment-one-sheet', 'Adventuring Gear', 0, 1),
('Longsword', '1d8', '/api/equipment/longsword', 'Weapon', 3, 15),
('Glassblower''s tools', null, '/api/equipment/glassblowers-tools', 'Tools', 5, 30),
('Warhammer', '1d8', '/api/equipment/warhammer', 'Weapon', 2, 15),
('Wooden staff', null, '/api/equipment/wooden-staff', 'Adventuring Gear', 4, 5),
('Waterskin', null, '/api/equipment/waterskin', 'Adventuring Gear', 5, 2),
('Woodcarver''s tools', null, '/api/equipment/woodcarvers-tools', 'Tools', 5, 1),
('Wand', null, '/api/equipment/wand', 'Adventuring Gear', 1, 10),
('Smith''s tools', null, '/api/equipment/smiths-tools', 'Tools', 8, 20),
('Tinderbox', null, '/api/equipment/tinderbox', 'Adventuring Gear', 1, 5),
('Saddle, Pack', null, '/api/equipment/saddle-pack', 'Mounts and Vehicles', 15, 5),
('Sling', '1d4', '/api/equipment/sling', 'Weapon', 0, 1),
('Tent, two-person', null, '/api/equipment/tent-two-person', 'Adventuring Gear', 20, 2),
('Spyglass', null, '/api/equipment/spyglass', 'Adventuring Gear', 1, 1000),
('Stabling (1 day)', null, '/api/equipment/stabling-1-day', 'Mounts and Vehicles', 0, 5),
('Staff', null, '/api/equipment/staff', 'Adventuring Gear', 4, 5),
('Torch', null, '/api/equipment/torch', 'Adventuring Gear', 1, 1),
('Studded Leather', null, '/api/equipment/studded-leather', 'Armor', 13, 45),
('Thieves'' tools', null, '/api/equipment/thieves-tools', 'Tools', 1, 25),
('Tinker''s tools', null, '/api/equipment/tinkers-tools', 'Tools', 10, 50),
('Saddlebags', null, '/api/equipment/saddlebags', 'Mounts and Vehicles', 8, 4),
('Poison, basic (vial)', null, '/api/equipment/poison-basic-vial', 'Adventuring Gear', 0, 100),
('Playing card set', null, '/api/equipment/playing-card-set', 'Tools', 0, 5),
('Pouch', null, '/api/equipment/pouch', 'Adventuring Gear', 1, 5),
('Mule', null, '/api/equipment/mule', 'Mounts and Vehicles', null, 8),
('Donkey', null, '/api/equipment/donkey', 'Mounts and Vehicles', null, 8),
('Keelboat', null, '/api/equipment/keelboat', 'Mounts and Vehicles', null, 3000),
('Dulcimer', null, '/api/equipment/dulcimer', 'Tools', 10, 25),
('Dungeoneer''s Pack', null, '/api/equipment/dungeoneers-pack', 'Adventuring Gear', null, 12),
('Fishing tackle', null, '/api/equipment/fishing-tackle', 'Adventuring Gear', 4, 1),
('Ram, portable', null, '/api/equipment/ram-portable', 'Adventuring Gear', 35, 4),
('Reliquary', null, '/api/equipment/reliquary', 'Adventuring Gear', 2, 5),
('Quiver', null, '/api/equipment/quiver', 'Adventuring Gear', 1, 1),
('Padded', null, '/api/equipment/padded', 'Armor', 8, 5),
('Navigator''s tools', null, '/api/equipment/navigators-tools', 'Tools', 2, 25),
('Pick, miner''s', null, '/api/equipment/pick-miners', 'Adventuring Gear', 10, 2),
('Paper (one sheet)', null, '/api/equipment/paper-one-sheet', 'Adventuring Gear', 0, 2),
('Antitoxin (vial)', null, '/api/equipment/antitoxin-vial', 'Adventuring Gear', 0, 50),
('Amulet', null, '/api/equipment/amulet', 'Adventuring Gear', 1, 5);
