INSERT INTO Proficiency
    (Name, api_link)
VALUES
("Brewer's supplies"),
("Alchemist's supplies"),
("Poisoner's Kit"),
("Disguise kit"),
("Darts"),
("Cartographer's tools"),
("Padded"),
("Heavy armor"),
("Leatherworker's tools"),
("Herbalism Kit"),
("Disguise kit"),
("Half Plate"),
("Breastplate"),
("All armor"),
("Calligrapher's supplies"),
("Blowguns"),
("Battleaxes"),
("Jeweler's tools"),
("Longbows"),
("Maces"),
("Glaives"),
("Plate"),
("Saving Throw: STR"),
("Shields"),
("Flute"),
("Shortswords"),
("Skill: Performance"),
("Morningstars"),
("Lute"),
("Saving Throw: INT"),
("Crossbows, hand"),
("Lances"),
("Skill: Persuasion"),
("Halberds"),
("Playing card set"),
("Bagpipes"),
("Light armor"),
("Saving Throw: CHA"),
("Chain Shirt"),
("Potter's tools"),
("Light hammers"),
("Greatclubs"),
("Flails"),
("Saving Throw: DEX"),
("Weaver's tools"),
("Crossbows, heavy"),
("Land Vehicles"),
("Woodcarver's tools"),
("Simple weapons"),
("Glassblower's tools"),
("Cook's utensils"),
("Tridents"),
("Martial weapons"),
("Dice Set"),
("Clubs"),
("Shortbows"),
("Carpenter's tools"),
("Mauls"),
("Scale Mail"),
("Pikes"),
("Handaxes"),
("Mason's tools"),
("Greatswords"),
("Dulcimer"),
("Quarterstaffs"),
("Daggers"),
("Javelins"),
("Skill: Medicine"),
("Skill: Insight"),
("Hide"),
("Tinker's tools"),
("Skill: Acrobatics"),
("Skill: Sleight of Hand"),
("Crossbows, light"),
("Forgery kit"),
("Rapiers"),
("Viol"),
("Slings"),
("Medium armor"),
("Painter's supplies"),
("Longswords"),
("Saving Throw: CON"),
("Skill: History"),
("Skill: Arcana"),
("Ring Mail"),
("Cobbler's tools"),
("Shawm"),
("Leather"),
("Nets"),
("Horn"),
("Saving Throw: WIS"),
("Forgery kit"),
("Skill: Perception"),
("Skill: Religion"),
("Water Vehicles"),
("Chain Mail"),
("Skill: Athletics"),
("Drum"),
("Skill: Animal Handling"),
("Studded Leather"),
("Three-Dragon Ante set"),
("Skill: Nature"),
("Thieves' Tools"),
("Shield"),
("Lyre"),
("Greataxes"),
("Skill: Survival"),
("War picks"),
("Skill: Deception"),
("Spears"),
("Dragonchess set"),
("Sickles"),
("Warhammers"),
("Scimitars"),
("Splint"),
("Navigator's Tools"),
("Pan flute"),
("Smith's tools"),
("Skill: Intimidation"),
("Whips"),
("Skill: Stealth"),
("Skill: Investigation"),