INSERT INTO proficiencies
    (name, api_link)
VALUES
("Cobbler's tools", "/api/proficiencies/cobblers-tools"),
("Leatherworker's tools", "/api/proficiencies/leatherworkers-tools"),
("Horn", "/api/proficiencies/horn"),
("Chain Mail", "/api/proficiencies/chain-mail"),
("All armor", "/api/proficiencies/all-armor"),
("Bagpipes", "/api/proficiencies/bagpipes"),
("Cartographer's tools", "/api/proficiencies/cartographers-tools"),
("Cook's utensils", "/api/proficiencies/cooks-utensils"),
("Martial weapons", "/api/proficiencies/martial-weapons"),
("Daggers", "/api/proficiencies/daggers"),
("Saving Throw: CHA", "/api/proficiencies/saving-throw-cha"),
("Glassblower's tools", "/api/proficiencies/glassblowers-tools"),
("Handaxes", "/api/proficiencies/handaxes"),
("Halberds", "/api/proficiencies/halberds"),
("Dice Set", "/api/proficiencies/dice-set"),
("Forgery kit", "/api/proficiencies/forgery-kit"),
("Chain Shirt", "/api/proficiencies/chain-shirt"),
("Clubs", "/api/proficiencies/clubs"),
("Battleaxes", "/api/proficiencies/battleaxes"),
("Playing card set", "/api/proficiencies/playing-card-set"),
("Navigator's Tools", "/api/proficiencies/navigators-tools"),
("Flails", "/api/proficiencies/flails"),
("Light armor", "/api/proficiencies/light-armor"),
("Crossbows, hand", "/api/proficiencies/crossbows-hand"),
("Crossbows, heavy", "/api/proficiencies/crossbows-heavy"),
("Ring Mail", "/api/proficiencies/ring-mail"),
("Breastplate", "/api/proficiencies/breastplate"),
("Half Plate", "/api/proficiencies/half-plate"),
("Greatswords", "/api/proficiencies/greatswords"),
("Blowguns", "/api/proficiencies/blowguns"),
("Painter's supplies", "/api/proficiencies/painters-supplies"),
("Saving Throw: CON", "/api/proficiencies/saving-throw-con"),
("Medium armor", "/api/proficiencies/medium-armor"),
("Padded", "/api/proficiencies/padded"),
("Drum", "/api/proficiencies/drum"),
("Potter's tools", "/api/proficiencies/potters-tools"),
("Shields", "/api/proficiencies/shields"),
("Calligrapher's supplies", "/api/proficiencies/calligraphers-supplies"),
("Lute", "/api/proficiencies/lute"),
("Greataxes", "/api/proficiencies/greataxes"),
("Maces", "/api/proficiencies/maces"),
("Alchemist's supplies", "/api/proficiencies/alchemists-supplies"),
("Saving Throw: DEX", "/api/proficiencies/saving-throw-dex"),
("Glaives", "/api/proficiencies/glaives"),
("Darts", "/api/proficiencies/darts"),
("Carpenter's tools", "/api/proficiencies/carpenters-tools"),
("Disguise kit", "/api/proficiencies/disguise-kit"),
("Nets", "/api/proficiencies/nets"),
("Crossbows, light", "/api/proficiencies/crossbows-light"),
("Disguise kit", "/api/proficiencies/disguise-kit"),
("Flute", "/api/proficiencies/flute"),
("Mauls", "/api/proficiencies/mauls"),
("Forgery kit", "/api/proficiencies/forgery-kit"),
("Pikes", "/api/proficiencies/pikes"),
("Heavy armor", "/api/proficiencies/heavy-armor"),
("Lyre", "/api/proficiencies/lyre"),
("Skill: Performance", "/api/proficiencies/skill-performance"),
("Skill: Medicine", "/api/proficiencies/skill-medicine"),
("Skill: Deception", "/api/proficiencies/skill-deception"),
("Skill: Insight", "/api/proficiencies/skill-insight"),
("Tridents", "/api/proficiencies/tridents"),
("Tinker's tools", "/api/proficiencies/tinkers-tools"),
("Hide", "/api/proficiencies/hide"),
("Herbalism Kit", "/api/proficiencies/herbalism-kit"),
("Shortbows", "/api/proficiencies/shortbows"),
("Mason's tools", "/api/proficiencies/masons-tools"),
("Skill: Acrobatics", "/api/proficiencies/skill-acrobatics"),
("Poisoner's Kit", "/api/proficiencies/poisoners-kit"),
("Pan flute", "/api/proficiencies/pan-flute"),
("Slings", "/api/proficiencies/slings"),
("Weaver's tools", "/api/proficiencies/weavers-tools"),
("Skill: Stealth", "/api/proficiencies/skill-stealth"),
("Plate", "/api/proficiencies/plate"),
("Light hammers", "/api/proficiencies/light-hammers"),
("Dulcimer", "/api/proficiencies/dulcimer"),
("Leather", "/api/proficiencies/leather"),
("Lances", "/api/proficiencies/lances"),
("Dragonchess set", "/api/proficiencies/dragonchess-set"),
("Javelins", "/api/proficiencies/javelins"),
("Skill: Intimidation", "/api/proficiencies/skill-intimidation"),
("Longswords", "/api/proficiencies/longswords"),
("Jeweler's tools", "/api/proficiencies/jewelers-tools"),
("Simple weapons", "/api/proficiencies/simple-weapons"),
("Rapiers", "/api/proficiencies/rapiers"),
("Land Vehicles", "/api/proficiencies/land-vehicles"),
("Spears", "/api/proficiencies/spears"),
("Saving Throw: INT", "/api/proficiencies/saving-throw-int"),
("Greatclubs", "/api/proficiencies/greatclubs"),
("Shield", "/api/proficiencies/shield"),
("Three-Dragon Ante set", "/api/proficiencies/three-dragon-ante-set"),
("Smith's tools", "/api/proficiencies/smiths-tools"),
("Saving Throw: WIS", "/api/proficiencies/saving-throw-wis"),
("Skill: Persuasion", "/api/proficiencies/skill-persuasion"),
("Skill: Survival", "/api/proficiencies/skill-survival"),
("Woodcarver's tools", "/api/proficiencies/woodcarvers-tools"),
("War picks", "/api/proficiencies/war-picks"),
("Scale Mail", "/api/proficiencies/scale-mail"),
("Studded Leather", "/api/proficiencies/studded-leather"),
("Skill: Perception", "/api/proficiencies/skill-perception"),
("Skill: History", "/api/proficiencies/skill-history"),
("Viol", "/api/proficiencies/viol"),
("Morningstars", "/api/proficiencies/morningstars"),
("Skill: Sleight of Hand", "/api/proficiencies/skill-sleight-of-hand"),
("Quarterstaffs", "/api/proficiencies/quarterstaffs"),
("Scimitars", "/api/proficiencies/scimitars"),
("Sickles", "/api/proficiencies/sickles"),
("Thieves' Tools", "/api/proficiencies/thieves-tools"),
("Whips", "/api/proficiencies/whips"),
("Skill: Athletics", "/api/proficiencies/skill-athletics"),
("Skill: Religion", "/api/proficiencies/skill-religion"),
("Skill: Nature", "/api/proficiencies/skill-nature"),
("Shawm", "/api/proficiencies/shawm"),
("Brewer's supplies", "/api/proficiencies/brewers-supplies"),
("Splint", "/api/proficiencies/splint"),
("Skill: Animal Handling", "/api/proficiencies/skill-animal-handling"),
("Shortswords", "/api/proficiencies/shortswords"),
("Longbows", "/api/proficiencies/longbows"),
("Warhammers", "/api/proficiencies/warhammers"),
("Saving Throw: STR", "/api/proficiencies/saving-throw-str"),
("Water Vehicles", "/api/proficiencies/water-vehicles"),
("Skill: Arcana", "/api/proficiencies/skill-arcana"),
("Skill: Investigation", "/api/proficiencies/skill-investigation");