INSERT INTO Abilities
    (Name, api_link)
VALUES
("Expertise: Insight", "/api/features/bard-expertise-insight"),
("Choose: Expertise 2", "/api/features/bard-choose-expertise-2"),
("Channel Divinity: Sacred Weapon", "/api/features/channel-divinity-sacred-weapon"),
("Choose: Multiattack", "/api/features/choose-multiattack"),
("Expertise: Sleight of Hand", "/api/features/bard-expertise-sleight-of-hand"),
("Aura of Devotion", "/api/features/aura-of-devotion"),
("Brutal Critical (1 die)", "/api/features/brutal-critical-1-die"),
("Bonus Proficiency", "/api/features/bonus-proficiency"),
("Channel Divinity: Preserve Life", "/api/features/channel-divinity-preserve-life"),
("Expertise: Athletics", "/api/features/bard-expertise-athletics"),
("Archdruid", "/api/features/archdruid"),
("Barbarian: Ability Score Improvement 4", "/api/features/barbarian-ability-score-improvement-4"),
("Aura of Protection", "/api/features/aura-of-protection"),
("Expertise: Nature", "/api/features/bard-expertise-nature"),
("Choose: Expertise 1", "/api/features/bard-choose-expertise-1"),
("Expertise: Deception", "/api/features/bard-expertise-deception"),
("Aura of Courage", "/api/features/aura-of-courage"),
("Bard: Ability Score Improvement 3", "/api/features/bard-ability-score-improvement-3"),
("Blessed Healer", "/api/features/blessed-healer"),
("Choose: Pact Boon", "/api/features/choose-pact-boon"),
("Channel Divinity: Turn the Unholy", "/api/features/channel-divinity-turn-the-unholy"),
("Expertise: Perception", "/api/features/bard-expertise-perception"),
("Bonus Cantrip", "/api/features/bonus-cantrip"),
("Bardic Inspiration (d10)", "/api/features/bardic-inspiration-d10"),
("Choose: Additional Eldritch Invocation", "/api/features/choose-additional-eldritch-invocation-2"),
("Choose: Dragon Ancestor", "/api/features/choose-dragon-ancestor"),
("Channel Divinity (3/rest)", "/api/features/channel-divinity-3-rest"),
("Cleric: Ability Score Improvement 1", "/api/features/cleric-ability-score-improvement-1"),
("Danger Sense", "/api/features/danger-sense"),
("Elusive", "/api/features/elusive"),
("Expertise: Religion", "/api/features/bard-expertise-religion"),
("Expertise: Medicine", "/api/features/bard-expertise-medicine"),
("Barbarian: Ability Score Improvement 5", "/api/features/barbarian-ability-score-improvement-5"),
("Expertise: Arcana", "/api/features/bard-expertise-arcana"),
("Brutal Critical (2 dice)", "/api/features/brutal-critical-2-dice"),
("Bardic Inspiration (d6)", "/api/features/bardic-inspiration-d6"),
("Arcane Tradition", "/api/features/arcane-tradition"),
("Channel Divinity: Turn Undead", "/api/features/channel-divinity-turn-undead"),
("Expertise: Acrobatics", "/api/features/bard-expertise-acrobatics"),
("Expertise: Stealth", "/api/features/bard-expertise-stealth"),
("Bard: Ability Score Improvement 4", "/api/features/bard-ability-score-improvement-4"),
("Expertise: Intimidation", "/api/features/bard-expertise-intimidation"),
("Barbarian: Ability Score Improvement 1", "/api/features/barbarian-ability-score-improvement-1"),
("Choose: Additional Eldritch Invocation", "/api/features/choose-additional-eldritch-invocation-5"),
("Expertise: History", "/api/features/bard-expertise-history"),
("Barbarian: Ability Score Improvement 3", "/api/features/barbarian-ability-score-improvement-3"),
("Bardic Inspiration (d12)", "/api/features/bardic-inspiration-d12"),
("Barbarian: Ability Score Improvement 2", "/api/features/barbarian-ability-score-improvement-2"),
("Channel Divinity", "/api/features/channel-divinity"),
("Arcane Recovery", "/api/features/arcane-recovery"),
("Additional Magical Secrets", "/api/features/additional-magical-secrets"),
("Domain Spells 5", "/api/features/domain-spells-5"),
("Bard: Ability Score Improvement 2", "/api/features/bard-ability-score-improvement-2"),
("Metamagic: Heightened Spell", "/api/features/metamagic-heightened-spell"),
("Extra Attack", "/api/features/barbarian-extra-attack"),
("Action Surge (1 use)", "/api/features/action-surge-1-use"),
("Choose: Hunter's Prey", "/api/features/choose-hunters-prey"),
("Expertise: Survival", "/api/features/bard-expertise-survival"),
("Expertise: Performance", "/api/features/bard-expertise-performance"),
("Expertise: Persuasion", "/api/features/bard-expertise-persuasion"),
("Choose: Additional Eldritch Invocation", "/api/features/choose-additional-eldritch-invocation-3"),
("Circle of the Land: Mountain", "/api/features/circle-of-the-land-mountain"),
("Circle of the Land: Forest", "/api/features/circle-of-the-land-forest"),
("Choose: Additional Fighting Style", "/api/features/choose-additional-fighting-style"),
("Channel Divinity (2/rest)", "/api/features/channel-divinity-2-rest"),
("Choose: Additional Metamagic", "/api/features/choose-additional-metamagic-2"),
("Draconic Presence", "/api/features/draconic-presence"),
("Aura improvements", "/api/features/aura-improvements"),
("Eldritch Invocation: Beguiling Influence", "/api/features/eldritch-invocation-beguiling-influence"),
("Circle Spells 1", "/api/features/circle-spells-1"),
("Action Surge (2 uses)", "/api/features/action-surge-2-uses"),
("Brutal Critical (3 dice)", "/api/features/brutal-critical-3-dice"),
("Unarmored Defense", "/api/features/barbarian-unarmored-defense"),
("Expertise: Animal Handling", "/api/features/bard-expertise-animal-handling"),
("Bard: Ability Score Improvement 1", "/api/features/bard-ability-score-improvement-1"),
("Eldritch Invocation: Visions of Distant Realms", "/api/features/eldritch-invocation-visions-of-distant-realms"),
("Blindsense", "/api/features/blindsense"),
("Choose: Additional Eldritch Invocation", "/api/features/choose-additional-eldritch-invocation-1"),
("Choose: Additional Eldritch Invocation", "/api/features/choose-additional-eldritch-invocation-4"),
("Bonus Proficiencies", "/api/features/bonus-proficiencies"),
("Circle of the Land: Desert", "/api/features/circle-of-the-land-desert"),
("Dragon Ancestor: Blue - Lightning Damage", "/api/features/dragon-ancestor-blue---lightning-damage"),
("Eldritch Invocation: Gaze of Two Minds", "/api/features/eldritch-invocation-gaze-of-two-minds"),
("Fighter: Ability Score Improvement 1", "/api/features/fighter-ability-score-improvement-1"),
("Diamond Soul", "/api/features/diamond-soul"),
("Circle of the Land: Coast", "/api/features/circle-of-the-land-coast"),
("Circle of the Land: Arctic", "/api/features/circle-of-the-land-arctic"),
("Dark One's Blessing", "/api/features/dark-ones-blessing"),
("Choose: Defensive Tactics", "/api/features/choose-defensive-tactics"),
("Fighting Style: Great Weapon Fighting", "/api/features/fighter-fighting-style-great-weapon-fighting"),
("Destroy Undead (CR 1/2 or below)", "/api/features/destroy-undead-cr-1-2-or-below"),
("Domain Spells 3", "/api/features/domain-spells-3"),
("Fighting Style: Dueling", "/api/features/fighter-fighting-style-dueling"),
("Bardic Inspiration (d8)", "/api/features/bardic-inspiration-d8"),
("Expertise: Persuasion", "/api/features/rogue-expertise-persuasion"),
("Eldritch Invocation: Dreadful Word", "/api/features/eldritch-invocation-dreadful-word"),
("Metamagic: Twinned Spell", "/api/features/metamagic-twinned-spell"),
("Evocation Savant", "/api/features/evocation-savant"),
("Cleric: Ability Score Improvement 5", "/api/features/cleric-ability-score-improvement-5"),
("Pact Magic", "/api/features/pact-magic"),
("Circle of the Land: Grassland", "/api/features/circle-of-the-land-grassland"),
("Expertise: Investigation", "/api/features/bard-expertise-investigation"),
("Beast Spells", "/api/features/beast-spells"),
("Choose: Fighting Style", "/api/features/fighter-choose-fighting-style"),
("Eldritch Invocation: Thirsting Blade", "/api/features/eldritch-invocation-thirsting-blade"),
("Choose: Superior Hunter's Defense", "/api/features/choose-superior-hunters-defense"),
("Circle of the Land: Swamp", "/api/features/circle-of-the-land-swamp"),
("Choose: Metamagic", "/api/features/choose-metamagic"),
("Eldritch Invocation: Beast Speech", "/api/features/eldritch-invocation-beast-speech"),
("Ranger: Ability Score Improvement 3", "/api/features/ranger-ability-score-improvement-3"),
("Empowered Evocation", "/api/features/empowered-evocation"),
("Deflect Missiles", "/api/features/deflect-missiles"),
("Circle Spells 2", "/api/features/circle-spells-2"),
("Cutting Words", "/api/features/cutting-words"),
("Intimidating Presence", "/api/features/intimidating-presence"),
("Divine Strike", "/api/features/divine-strike"),
("Extra Attack (1)", "/api/features/extra-attack-1"),
("Choose: Additional Metamagic", "/api/features/choose-additional-metamagic-1"),
("Fighting Style: Protection", "/api/features/fighting-style-protection"),
("Feral Senses", "/api/features/feral-senses"),
("Favored Enemy (2 types)", "/api/features/favored-enemy-2-types"),
("Empty Body", "/api/features/empty-body"),
("Divine Sense", "/api/features/divine-sense"),
("Eldritch Invocation: Whispers of the Grave", "/api/features/eldritch-invocation-whispers-of-the-grave"),
("Bard College", "/api/features/bard-college"),
("Nature's Sanctuary", "/api/features/natures-sanctuary"),
("Draconic Resilience", "/api/features/draconic-resilience"),
("Fighting Style: Two-Weapon Fighting", "/api/features/fighter-fighting-style-two-weapon-fighting"),
("Eldritch Invocation: Minions of Chaos", "/api/features/eldritch-invocation-minions-of-chaos"),
("Fighting Style: Archery", "/api/features/fighter-fighting-style-archery"),
("Choose: Circle of the Land", "/api/features/choose-circle-of-the-land"),
("Favored Enemy (1 type)", "/api/features/favored-enemy-1-type"),
("Choose: Additional Eldritch Invocation", "/api/features/choose-additional-eldritch-invocation-6"),
("Choose: Eldritch Invocations", "/api/features/choose-eldritch-invocations"),
("Eldritch Invocation: Eyes of the Rune Keeper", "/api/features/eldritch-invocation-eyes-of-the-rune-keeper"),
("Choose: Additional Eldritch Invocation", "/api/features/choose-additional-eldritch-invocation-7"),
("Eldritch Invocation: Book of Ancient Secrets", "/api/features/eldritch-invocation-book-of-ancient-secrets"),
("Channel Divinity (1/rest)", "/api/features/channel-divinity-1-rest"),
("Circle Spells 4", "/api/features/circle-spells-4"),
("Eldritch Invocation: Master of Myriad Forms", "/api/features/eldritch-invocation-master-of-myriad-forms"),
("Destroy Undead (CR 4 or below)", "/api/features/destroy-undead-cr-4-or-below"),
("Fast Movement", "/api/features/fast-movement"),
("Cleansing Touch", "/api/features/cleansing-touch"),
("Domain Spells 2", "/api/features/domain-spells-2"),
("Elemental Affinity", "/api/features/elemental-affinity"),
("Flexible Casting: Converting Spell Slot", "/api/features/flexible-casting-converting-spell-slot"),
("Fighter: Ability Score Improvement 2", "/api/features/fighter-ability-score-improvement-2"),
("Fighter: Ability Score Improvement 5", "/api/features/fighter-ability-score-improvement-5"),
("Circle Spells 3", "/api/features/circle-spells-3"),
("Divine Health", "/api/features/divine-health"),
("Vanish", "/api/features/vanish"),
("Divine Smite", "/api/features/divine-smite"),
("Defensive Tactics: Steel Will", "/api/features/defensive-tactics-steel-will"),
("Divine Intervention", "/api/features/divine-intervention"),
("Dragon Ancestor: Brass - Fire Damage", "/api/features/dragon-ancestor-brass---fire-damage"),
("Eldritch Invocation: Chains of Carceri", "/api/features/eldritch-invocation-chains-of-carceri"),
("Hide in Plain Sight", "/api/features/hide-in-plain-sight"),
("Countercharm", "/api/features/countercharm"),
("Font of Magic", "/api/features/font-of-magic"),
("Stillness of Mind", "/api/features/stillness-of-mind"),
("Cleric: Ability Score Improvement 2", "/api/features/cleric-ability-score-improvement-2"),
("Disciple of Life", "/api/features/disciple-of-life"),
("Fighting Style: Protection", "/api/features/fighter-fighting-style-protection"),
("Dragon Ancestor: Black - Acid Damage", "/api/features/dragon-ancestor-black---acid-damage"),
("Eldritch Master", "/api/features/eldritch-master"),
("Domain Spells 4", "/api/features/domain-spells-4"),
("Bard: Ability Score Improvement 5", "/api/features/bard-ability-score-improvement-5"),
("Dragon Ancestor: Silver - Cold Damage", "/api/features/dragon-ancestor-silver---cold-damage"),
("Druid: Ability Score Improvement 4", "/api/features/druid-ability-score-improvement-4"),
("Destroy Undead (CR 2 or below)", "/api/features/destroy-undead-cr-2-or-below"),
("Dragon Wings", "/api/features/dragon-wings"),
("Defensive Tactics: Multiattack Defense", "/api/features/defensive-tactics-multiattack-defense"),
("Druid: Ability Score Improvement 3", "/api/features/druid-ability-score-improvement-3"),
("Druid: Ability Score Improvement 5", "/api/features/druid-ability-score-improvement-5"),
("Dragon Ancestor: Gold - Fire Damage", "/api/features/dragon-ancestor-gold---fire-damage"),
("Indomitable (1 use)", "/api/features/indomitable-1-use"),
("Druidic", "/api/features/druidic"),
("Druid Circle", "/api/features/druid-circle"),
("Timeless Body", "/api/features/druid-timeless-body"),
("Domain Spells 1", "/api/features/domain-spells-1"),
("Cleric: Ability Score Improvement 3", "/api/features/cleric-ability-score-improvement-3"),
("Dark One's Own Luck", "/api/features/dark-ones-own-luck"),
("Defensive Tactics: Escape the Horde", "/api/features/defensive-tactics-escape-the-horde"),
("Indomitable (2 uses)", "/api/features/indomitable-2-uses"),
("Druid: Ability Score Improvement 1", "/api/features/druid-ability-score-improvement-1"),
("Destroy Undead (CR 1 or below)", "/api/features/destroy-undead-cr-1-or-below"),
("Cleric: Ability Score Improvement 4", "/api/features/cleric-ability-score-improvement-4"),
("Dragon Ancestor: Bronze - Lightning Damage", "/api/features/dragon-ancestor-bronze---lightning-damage"),
("Divine Domain", "/api/features/divine-domain"),
("Improved Divine Smite", "/api/features/improved-divine-smite"),
("Cunning Action", "/api/features/cunning-action"),
("Dragon Ancestor: White - Cold Damage", "/api/features/dragon-ancestor-white---cold-damage"),
("Land's Stride", "/api/features/druid-lands-stride"),
("Eldritch Invocation: Mire the Mind", "/api/features/eldritch-invocation-mire-the-mind"),
("Fighting Style: Great Weapon Fighting", "/api/features/fighting-style-great-weapon-fighting"),
("Hunter's Prey: Giant Killer", "/api/features/hunters-prey-giant-killer"),
("Divine Intervention Improvement", "/api/features/divine-intervention-improvement"),
("Hunter's Prey: Colossus Slayer", "/api/features/hunters-prey-colossus-slayer"),
("Destroy Undead (CR 3 or below)", "/api/features/destroy-undead-cr-3-or-below"),
("Improved Critical", "/api/features/improved-critical"),
("Indomitable Might", "/api/features/indomitable-might"),
("Dragon Ancestor: Green - Poison Damage", "/api/features/dragon-ancestor-green---poison-damage"),
("Indomitable (3 uses)", "/api/features/indomitable-3-uses"),
("Druid: Ability Score Improvement 2", "/api/features/druid-ability-score-improvement-2"),
("Foe Slayer", "/api/features/foe-slayer"),
("Dragon Ancestor: Copper - Acid Damage", "/api/features/dragon-ancestor-copper---acid-damage"),
("Hurl Through Hell", "/api/features/hurl-through-hell"),
("Dragon Ancestor: Red - Fire Damage", "/api/features/dragon-ancestor-red---fire-damage"),
("Hunter's Prey: Horde Breaker", "/api/features/hunters-prey-horde-breaker"),
("Eldritch Invocation: Agonizing Blast", "/api/features/eldritch-invocation-agonizing-blast"),
("Eldritch Invocation: Thief of Five Fates", "/api/features/eldritch-invocation-thief-of-five-fates"),
("Eldritch Invocation: Otherworldly Leap", "/api/features/eldritch-invocation-otherworldly-leap"),
("Extra Attack (2)", "/api/features/extra-attack-2"),
("Eldritch Invocation: Mask of Many Faces", "/api/features/eldritch-invocation-mask-of-many-faces"),
("Feral Instinct", "/api/features/feral-instinct"),
("Eldritch Invocation: Bewitching Whispers", "/api/features/eldritch-invocation-bewitching-whispers"),
("Eldritch Invocation: Sign of Ill Omen", "/api/features/eldritch-invocation-sign-of-ill-omen"),
("Fighter: Ability Score Improvement 3", "/api/features/fighter-ability-score-improvement-3"),
("Fiendish Resilience", "/api/features/fiendish-resilience"),
("Eldritch Invocation: Sculptor of Flesh", "/api/features/eldritch-invocation-sculptor-of-flesh"),
("Fast Hands", "/api/features/fast-hands"),
("Eldritch Invocation: Voice of the Chain Master", "/api/features/eldritch-invocation-voice-of-the-chain-master"),
("Eldritch Invocation: Eldritch Sight", "/api/features/eldritch-invocation-eldritch-sight"),
("Eldritch Invocation: Repelling Blast", "/api/features/eldritch-invocation-repelling-blast"),
("Eldritch Invocation: Lifedrinker", "/api/features/eldritch-invocation-lifedrinker"),
("Eldritch Invocation: Armor of Shadows", "/api/features/eldritch-invocation-armor-of-shadows"),
("Fighting Style: Defense", "/api/features/fighting-style-defense"),
("Frenzy", "/api/features/frenzy"),
("Font of Inspiration", "/api/features/font-of-inspiration"),
("Eldritch Invocation: Fiendish Vigor", "/api/features/eldritch-invocation-fiendish-vigor"),
("Flexible Casting: Creating Spell Slots", "/api/features/flexible-casting-creating-spell-slots"),
("Eldritch Invocation: Witch Sight", "/api/features/eldritch-invocation-witch-sight"),
("Extra Attack (3)", "/api/features/extra-attack-3"),
("Favored Enemy (3 enemies)", "/api/features/favored-enemy-3-enemies"),
("Flurry of Blows", "/api/features/flurry-of-blows"),
("Eldritch Invocation: Ascendant Step", "/api/features/eldritch-invocation-ascendant-step"),
("Fighting Style: Dueling", "/api/features/fighting-style-dueling"),
("Eldritch Invocation: Misty Visions", "/api/features/eldritch-invocation-misty-visions"),
("Eldritch Invocation: Eldritch Spear", "/api/features/eldritch-invocation-eldritch-spear"),
("Fighting Style: Defense", "/api/features/fighter-fighting-style-defense"),
("Fighter: Ability Score Improvement 7", "/api/features/fighter-ability-score-improvement-7"),
("Eldritch Invocation: One with Shadows", "/api/features/eldritch-invocation-one-with-shadows"),
("Fighter: Ability Score Improvement 6", "/api/features/fighter-ability-score-improvement-6"),
("Fighter: Ability Score Improvement 4", "/api/features/fighter-ability-score-improvement-4"),
("Eldritch Invocation: Devil's Sight", "/api/features/eldritch-invocation-devils-sight"),
("Song of Rest (d8)", "/api/features/song-of-rest-d8"),
("Thieves' Cant", "/api/features/thieves-cant"),
("Survivor", "/api/features/survivor"),
("Rogue: Ability Score Improvement 3", "/api/features/rogue-ability-score-improvement-3"),
("Ranger: Ability Score Improvement 1", "/api/features/ranger-ability-score-improvement-1"),
("Natural Explorer (2 terrain types)", "/api/features/natural-explorer-2-terrain-types"),
("Supreme Healing", "/api/features/supreme-healing"),
("Expertise: Acrobatics", "/api/features/rogue-expertise-acrobatics"),
("Expertise: Thieves' Tools", "/api/features/rogue-expertise-thieves-tools"),
("Relentless Rage", "/api/features/relentless-rage"),
("Wizard: Ability Score Improvement 2", "/api/features/wizard-ability-score-improvement-2"),
("Wild Shape (CR 1/4 or below, no flying or swim speed)", "/api/features/wild-shape-cr-1-4-or-below-no-flying-or-swim-speed"),
("Warlock: Ability Score Improvement 2", "/api/features/warlock-ability-score-improvement-2"),
("Sorcerous Origin", "/api/features/sorcerous-origin"),
("Otherworldly Patron", "/api/features/otherworldly-patron"),
("Warlock: Ability Score Improvement 1", "/api/features/warlock-ability-score-improvement-1"),
("Expertise: History", "/api/features/rogue-expertise-history"),
("Rogue: Ability Score Improvement 5", "/api/features/rogue-ability-score-improvement-5"),
("Magical Secrets 3", "/api/features/magical-secrets-3"),
("Expertise: Athletics", "/api/features/rogue-expertise-athletics"),
("Metamagic: Subtle Spell", "/api/features/metamagic-subtle-spell"),
("Unarmored Defense", "/api/features/monk-unarmored-defense"),
("Magical Secrets 1", "/api/features/magical-secrets-1"),
("Ranger: Ability Score Improvement 2", "/api/features/ranger-ability-score-improvement-2"),
("Rage", "/api/features/rage"),
("Metamagic: Empowered Spell", "/api/features/metamagic-empowered-spell"),
("Reckless Attack", "/api/features/reckless-attack"),
("Mystic Arcanum (7th level)", "/api/features/mystic-arcanum-7th-level"),
("Expertise: Stealth", "/api/features/rogue-expertise-stealth"),
("Expertise: Perception", "/api/features/rogue-expertise-perception"),
("Stunning Strike", "/api/features/stunning-strike"),
("Martial Arts", "/api/features/martial-arts"),
("Choose: Fighting Style", "/api/features/ranger-choose-fighting-style"),
("Sorcerer: Ability Score Improvement 5", "/api/features/sorcerer-ability-score-improvement-5"),
("Purity of Body", "/api/features/purity-of-body"),
("Natural Explorer (1 terrain type)", "/api/features/natural-explorer-1-terrain-type"),
("Uncanny Dodge", "/api/features/uncanny-dodge"),
("Spellcasting: Sorcerer", "/api/features/spellcasting-sorcerer"),
("Expertise: Animal Handling", "/api/features/rogue-expertise-animal-handling"),
("Thief's Reflexes", "/api/features/thiefs-reflexes"),
("Spellcasting: Paladin", "/api/features/spellcasting-paladin"),
("Rogue: Ability Score Improvement 6", "/api/features/rogue-ability-score-improvement-6"),
("Retaliation", "/api/features/retaliation"),
("Paladin: Ability Score Improvement 5", "/api/features/paladin-ability-score-improvement-5"),
("Paladin: Ability Score Improvement 1", "/api/features/paladin-ability-score-improvement-1"),
("Supreme Sneak", "/api/features/supreme-sneak"),
("Oath Spells", "/api/features/oath-spells"),
("Song of Rest (d12)", "/api/features/song-of-rest-d12"),
("Rogue: Ability Score Improvement 1", "/api/features/rogue-ability-score-improvement-1"),
("Unarmored Movement 1", "/api/features/unarmored-movement-1"),
("Land's Stride", "/api/features/ranger-lands-stride"),
("Expertise: Nature", "/api/features/rogue-expertise-nature"),
("Monk: Ability Score Improvement 3", "/api/features/monk-ability-score-improvement-3"),
("Nature's Ward", "/api/features/natures-ward"),
("Expertise: Deception", "/api/features/rogue-expertise-deception"),
("Wizard: Ability Score Improvement 5", "/api/features/wizard-ability-score-improvement-5"),
("Pact of the Chain", "/api/features/pact-of-the-chain"),
("Superior Hunter's Defense: Stand Against the Tide", "/api/features/superior-hunters-defense-stand-against-the-tide"),
("Multiattack: Volley", "/api/features/multiattack-volley"),
("Ranger: Ability Score Improvement 5", "/api/features/ranger-ability-score-improvement-5"),
("Mystic Arcanum (9th level)", "/api/features/mystic-arcanum-9th-level"),
("Primal Champion", "/api/features/primal-champion"),
("Expertise: Investigation", "/api/features/rogue-expertise-investigation"),
("Peerless Skill", "/api/features/peerless-skill"),
("Second-Story Work", "/api/features/second-story-work"),
("Lay on Hands", "/api/features/lay-on-hands"),
("Remarkable Athlete", "/api/features/remarkable-athlete"),
("Ki Empowered Strikes", "/api/features/ki-empowered-strikes"),
("Sorcerer: Ability Score Improvement 1", "/api/features/sorcerer-ability-score-improvement-1"),
("Superior Inspiration", "/api/features/superior-inspiration"),
("Tongue of the Sun and Moon", "/api/features/tongue-of-the-sun-and-moon"),
("Sneak Attack", "/api/features/sneak-attack"),
("Nimbus", "/api/features/nimbus"),
("Ki", "/api/features/ki"),
("Superior Hunter's Defense: Evasion", "/api/features/superior-hunters-defense-evasion"),
("Metamagic: Distant Spell", "/api/features/metamagic-distant-spell"),
("Wild Shape (CR 1 or below)", "/api/features/wild-shape-cr-1-or-below"),
("Pact of the Blade", "/api/features/pact-of-the-blade"),
("Open Hand Technique", "/api/features/open-hand-technique"),
("Sorcerous Restoration", "/api/features/sorcerous-restoration"),
("Wizard: Ability Score Improvement 4", "/api/features/wizard-ability-score-improvement-4"),
("Use Magic Device", "/api/features/use-magic-device"),
("Mystic Arcanum (8th level)", "/api/features/mystic-arcanum-8th-level"),
("Expertise: Performance", "/api/features/rogue-expertise-performance"),
("Spellcasting: Cleric", "/api/features/spellcasting-cleric"),
("Natural Explorer (3 terrain types)", "/api/features/natural-explorer-3-terrain-types"),
("Fighting Style: Archery", "/api/features/ranger-fighting-style-archery"),
("Potent Cantrip", "/api/features/potent-cantrip"),
("Choose: Fighting Style", "/api/features/paladin-choose-fighting-style"),
("Perfect Self", "/api/features/perfect-self"),
("Sorcerer: Ability Score Improvement 4", "/api/features/sorcerer-ability-score-improvement-4"),
("Spell Mastery", "/api/features/spell-mastery"),
("Extra Attack", "/api/features/paladin-extra-attack"),
("Expertise: Insight", "/api/features/rogue-expertise-insight"),
("Mystic Arcanum (6th level)", "/api/features/mystic-arcanum-6th-level"),
("Persistent Rage", "/api/features/persistent-rage"),
("Metamagic: Careful Spell", "/api/features/metamagic-careful-spell"),
("Monk: Ability Score Improvement 2", "/api/features/monk-ability-score-improvement-2"),
("Wizard: Ability Score Improvement 3", "/api/features/wizard-ability-score-improvement-3"),
("Extra Attack", "/api/features/monk-extra-attack"),
("Evasion", "/api/features/monk-evasion"),
("Ranger: Ability Score Improvement 4", "/api/features/ranger-ability-score-improvement-4"),
("Warlock: Ability Score Improvement 4", "/api/features/warlock-ability-score-improvement-4"),
("Unarmored Movement 2", "/api/features/unarmored-movement-2"),
("Spellcasting: Bard", "/api/features/spellcasting-bard"),
("Spellcasting: Druid", "/api/features/spellcasting-druid"),
("Song of Rest (d6)", "/api/features/song-of-rest-d6"),
("Sorcerer: Ability Score Improvement 2", "/api/features/sorcerer-ability-score-improvement-2"),
("Natural Recovery", "/api/features/natural-recovery"),
("Extra Attack", "/api/features/ranger-extra-attack"),
("Step of the Wind", "/api/features/step-of-the-wind"),
("Expertise: Arcana", "/api/features/rogue-expertise-arcana"),
("Expertise: Religion", "/api/features/rogue-expertise-religion"),
("Timeless Body", "/api/features/monk-timeless-body"),
("Expertise: Survival", "/api/features/rogue-expertise-survival"),
("Paladin: Ability Score Improvement 2", "/api/features/paladin-ability-score-improvement-2"),
("Signature Spell", "/api/features/signature-spell"),
("Tranquility", "/api/features/tranquility"),
("Spellcasting: Wizard", "/api/features/spellcasting-wizard"),
("Rogue: Ability Score Improvement 4", "/api/features/rogue-ability-score-improvement-4"),
("Overchannel", "/api/features/overchannel"),
("Slow Fall", "/api/features/slow-fall"),
("Metamagic: Quickened Spell", "/api/features/metamagic-quickened-spell"),
("Rogue: Ability Score Improvement 2", "/api/features/rogue-ability-score-improvement-2"),
("Wizard: Ability Score Improvement 1", "/api/features/wizard-ability-score-improvement-1"),
("Monastic Tradition", "/api/features/monastic-tradition"),
("Paladin: Ability Score Improvement 3", "/api/features/paladin-ability-score-improvement-3"),
("Multiattack: Whirlwind Attack", "/api/features/multiattack-whirlwind-attack"),
("Monk: Ability Score Improvement 5", "/api/features/monk-ability-score-improvement-5"),
("Choose: Expertise 2", "/api/features/rogue-choose-expertise-2"),
("Second Wind", "/api/features/second-wind"),
("Expertise: Intimidation", "/api/features/rogue-expertise-intimidation"),
("Monk: Ability Score Improvement 4", "/api/features/monk-ability-score-improvement-4"),
("Wholeness of Body", "/api/features/wholeness-of-body"),
("Slippery Mind", "/api/features/slippery-mind"),
("Warlock: Ability Score Improvement 5", "/api/features/warlock-ability-score-improvement-5"),
("Superior Hunter's Defense: Uncanny Dodge", "/api/features/superior-hunters-defense-uncanny-dodge"),
("Stroke of Luck", "/api/features/stroke-of-luck"),
("Spellcasting: Ranger", "/api/features/spellcasting-ranger"),
("Choose: Expertise 1", "/api/features/rogue-choose-expertise-1"),
("Sculpt Spells", "/api/features/sculpt-spells"),
("Song of Rest (d10)", "/api/features/song-of-rest-d10"),
("Sacred Oath", "/api/features/sacred-oath"),
("Metamagic: Extended Spell", "/api/features/metamagic-extended-spell"),
("Superior Critical", "/api/features/superior-critical"),
("Purity of Spirit", "/api/features/purity-of-spirit"),
("Patient Defense", "/api/features/patient-defense"),
("Jack of All Trades", "/api/features/jack-of-all-trades"),
("Wild Shape (CR 1/2 or below, no flying speed)", "/api/features/wild-shape-cr-1-2-or-below-no-flying-speed"),
("Martial Archetype", "/api/features/martial-archetype"),
("Ranger Archetype", "/api/features/ranger-archetype"),
("Fighting Style: Two-Weapon Fighting", "/api/features/ranger-fighting-style-two-weapon-fighting"),
("Primeval Awareness", "/api/features/primeval-awareness"),
("Warlock: Ability Score Improvement 3", "/api/features/warlock-ability-score-improvement-3"),
("Expertise: Medicine", "/api/features/rogue-expertise-medicine"),
("Expertise: Sleight of Hand", "/api/features/rogue-expertise-sleight-of-hand"),
("Quivering Palm", "/api/features/quivering-palm"),
("Monk: Ability Score Improvement 1", "/api/features/monk-ability-score-improvement-1"),
("Evasion", "/api/features/rogue-evasion"),
("Reliable Talent", "/api/features/reliable-talent"),
("Sorcerer: Ability Score Improvement 3", "/api/features/sorcerer-ability-score-improvement-3"),
("Magical Secrets 2", "/api/features/magical-secrets-2"),
("Pact of the Tome", "/api/features/pact-of-the-tome"),
("Fighting Style: Defense", "/api/features/ranger-fighting-style-defense"),
("Mindless Rage", "/api/features/mindless-rage"),
("Paladin: Ability Score Improvement 4", "/api/features/paladin-ability-score-improvement-4"),
("Roguish Archetype", "/api/features/roguish-archetype"),
("Fighting Style: Dueling", "/api/features/ranger-fighting-style-dueling"),
("Primal Path", "/api/features/primal-path");