INSERT INTO spells
    (name, spell_level, duration, is_ritual, casting_time, range, api_link)
VALUES
('False Life', 1, '1 hour', false, '1 action', 'Self', '/api/spells/false-life'),
('Find Familiar', 1, 'Instantaneous', true, '1 hour', '10 feet', '/api/spells/find-familiar'),
('Antimagic Field', 8, 'Up to 1 hour', false, '1 action', 'Self', '/api/spells/antimagic-field'),
('Acid Arrow', 2, 'Instantaneous', false, '1 action', '90 feet', '/api/spells/acid-arrow'),
('Freezing Sphere', 6, 'Instantaneous', false, '1 action', '300 feet', '/api/spells/freezing-sphere'),
('Blade Barrier', 6, 'Up to 10 minutes', false, '1 action', '90 feet', '/api/spells/blade-barrier'),
('Private Sanctum', 4, '24 hours', false, '10 minutes', '120 feet', '/api/spells/private-sanctum'),
('Protection from Energy', 3, 'Up to 1 hour', false, '1 action', 'Touch', '/api/spells/protection-from-energy'),
('Beacon of Hope', 3, 'Up to 1 minute', false, '1 action', '30 feet', '/api/spells/beacon-of-hope'),
('Dimension Door', 4, 'Instantaneous', false, '1 action', '500 feet', '/api/spells/dimension-door'),
('Vicious Mockery', 0, 'Instantaneous', false, '1 action', '60 feet', '/api/spells/vicious-mockery'),
('Wall of Ice', 6, 'Up to 10 minutes', false, '1 action', '120 feet', '/api/spells/wall-of-ice'),
('Wish', 9, 'Instantaneous', false, '1 action', 'Self', '/api/spells/wish'),
('Cure Wounds', 1, 'Instantaneous', false, '1 action', 'Touch', '/api/spells/cure-wounds'),
('Wall of Stone', 5, 'Up to 10 minutes', false, '1 action', '120 feet', '/api/spells/wall-of-stone'),
('Enhance Ability', 2, 'Up to 1 hour', false, '1 action', 'Touch', '/api/spells/enhance-ability'),
('Darkness', 2, 'Up to 10 minutes', false, '1 action', '60 feet', '/api/spells/darkness'),
('Wind Walk', 6, '8 hours', false, '1 minute', '30 feet', '/api/spells/wind-walk'),
('Wall of Fire', 4, 'Up to 1 minute', false, '1 action', '120 feet', '/api/spells/wall-of-fire'),
('Wall of Force', 5, 'Up to 10 minutes', false, '1 action', '120 feet', '/api/spells/wall-of-force'),
('Arcane Lock', 2, 'Until dispelled', false, '1 action', 'Touch', '/api/spells/arcane-lock'),
('Animal Messenger', 2, '24 hours', true, '1 action', '30 feet', '/api/spells/animal-messenger'),
('Cone of Cold', 5, 'Instantaneous', false, '1 action', 'Self', '/api/spells/cone-of-cold'),
('Augury', 2, 'Instantaneous', true, '1 minute', 'Self', '/api/spells/augury'),
('Control Weather', 8, 'Up to 8 hours', false, '10 minutes', 'Self', '/api/spells/control-weather'),
('Message', 0, '1 round', false, '1 action', '120 feet', '/api/spells/message'),
('Passwall', 5, '1 hour', false, '1 action', '30 feet', '/api/spells/passwall'),
('Power Word Kill', 9, 'Instantaneous', false, '1 action', '60 feet', '/api/spells/power-word-kill'),
('Chill Touch', 0, '1 round', false, '1 action', '120 feet', '/api/spells/chill-touch'),
('Dispel Evil and Good', 5, 'Up to 1 minute', false, '1 action', 'Self', '/api/spells/dispel-evil-and-good'),
('Druidcraft', 0, 'Instantaneous', false, '1 action', '30 feet', '/api/spells/druidcraft'),
('Fire Shield', 4, '10 minutes', false, '1 action', 'Self', '/api/spells/fire-shield'),
('Barkskin', 2, 'Up to 1 hour', false, '1 action', 'Touch', '/api/spells/barkskin'),
('Polymorph', 4, 'Up to 1 hour', false, '1 action', '60 feet', '/api/spells/polymorph'),
('Sleet Storm', 3, 'Up to 1 minute', false, '1 action', '150 feet', '/api/spells/sleet-storm'),
('Shield', 1, '1 round', false, '1 reaction', 'Self', '/api/spells/shield'),
('Regenerate', 7, '1 hour', false, '1 minute', 'Touch', '/api/spells/regenerate'),
('Speak with Animals', 1, '10 minutes', true, '1 action', 'Self', '/api/spells/speak-with-animals'),
('Fear', 3, 'Up to 1 minute', false, '1 action', 'Self', '/api/spells/fear'),
('Magic Jar', 6, 'Until dispelled', false, '1 minute', 'Self', '/api/spells/magic-jar'),
('Cloudkill', 5, 'Up to 10 minutes', false, '1 action', '120 feet', '/api/spells/cloudkill'),
('Scrying', 5, 'Up to 10 minutes', false, '10 minutes', 'Self', '/api/spells/scrying'),
('Resilient Sphere', 4, 'Up to 1 minute', false, '1 action', '30 feet', '/api/spells/resilient-sphere'),
('Prayer of Healing', 2, 'Instantaneous', false, '10 minutes', '30 feet', '/api/spells/prayer-of-healing'),
('Revivify', 3, 'Instantaneous', false, '1 action', 'Touch', '/api/spells/revivify'),
('Sacred Flame', 0, 'Instantaneous', false, '1 action', '60 feet', '/api/spells/sacred-flame'),
('True Resurrection', 9, 'Instantaneous', false, '1 hour', 'Touch', '/api/spells/true-resurrection'),
('Conjure Elemental', 5, 'Up to 1 hour', false, '1 minute', '90 feet', '/api/spells/conjure-elemental'),
('Contact Other Plane', 5, '1 minute', true, '1 minute', 'Self', '/api/spells/contact-other-plane'),
('Color Spray', 1, '1 round', false, '1 action', 'Self', '/api/spells/color-spray'),
('Hold Person', 2, 'Up to 1 minute', false, '1 action', '60 feet', '/api/spells/hold-person'),
('Conjure Minor Elementals', 4, 'Up to 1 hour', false, '1 minute', '90 feet', '/api/spells/conjure-minor-elementals'),
('Conjure Woodland Beings', 4, 'Up to 1 hour', false, '1 action', '60 feet', '/api/spells/conjure-woodland-beings'),
('Feather Fall', 1, '1 minute', false, '1 reaction', '60 feet', '/api/spells/feather-fall'),
('Prestidigitation', 0, '1 hour', false, '1 action', '10 feet', '/api/spells/prestidigitation'),
('Conjure Animals', 3, 'Up to 1 hour', false, '1 action', '60 feet', '/api/spells/conjure-animals'),
('Fire Bolt', 0, 'Instantaneous', false, '1 action', '120 feet', '/api/spells/fire-bolt'),
('Arcanist''s Magic Aura', 2, '24 hours', false, '1 action', 'Touch', '/api/spells/arcanists-magic-aura'),
('Scorching Ray', 2, 'Instantaneous', false, '1 action', '120 feet', '/api/spells/scorching-ray'),
('See Invisibility', 2, '1 hour', false, '1 action', 'Self', '/api/spells/see-invisibility'),
('Sunburst', 8, 'Instantaneous', false, '1 action', '150 feet', '/api/spells/sunburst'),
('Programmed Illusion', 6, 'Until dispelled', false, '1 action', '120 feet', '/api/spells/programmed-illusion'),
('Plane Shift', 7, 'Instantaneous', false, '1 action', 'Touch', '/api/spells/plane-shift'),
('Find the Path', 6, 'Up to 24 hours', false, '1 minute', 'Self', '/api/spells/find-the-path'),
('Protection from Evil and Good', 1, 'Up to 10 minutes', false, '1 action', 'Touch', '/api/spells/protection-from-evil-and-good'),
('Feeblemind', 8, 'Instantaneous', false, '1 action', '150 feet', '/api/spells/feeblemind'),
('Mislead', 5, 'Up to 1 hour', false, '1 action', 'Self', '/api/spells/mislead'),
('Blight', 4, 'Instantaneous', false, '1 action', '30 feet', '/api/spells/blight'),
('Plant Growth', 3, 'Instantaneous', false, '1 action', '150 feet', '/api/spells/plant-growth'),
('Arcane Eye', 4, 'Up to 1 hour', false, '1 action', '30 feet', '/api/spells/arcane-eye'),
('Antipathy/Sympathy', 8, '10 days', false, '1 hour', '60 feet', '/api/spells/antipathy-sympathy'),
('Tree Stride', 5, 'Up to 1 minute', false, '1 action', 'Self', '/api/spells/tree-stride'),
('Find Steed', 2, 'Instantaneous', false, '10 minutes', '30 feet', '/api/spells/find-steed'),
('Meteor Swarm', 9, 'Instantaneous', false, '1 action', '1 mile', '/api/spells/meteor-swarm'),
('True Polymorph', 9, 'Up to 1 hour', false, '1 action', '30 feet', '/api/spells/true-polymorph'),
('Magic Weapon', 2, 'Up to 1 hour', false, '1 bonus action', 'Touch', '/api/spells/magic-weapon'),
('Transport via Plants', 6, '1 round', false, '1 action', '10 feet', '/api/spells/transport-via-plants'),
('Calm Emotions', 2, 'Up to 1 minute', false, '1 action', '60 feet', '/api/spells/calm-emotions'),
('Mass Cure Wounds', 5, 'Instantaneous', false, '1 action', '60 feet', '/api/spells/mass-cure-wounds'),
('Unseen Servant', 1, '1 hour', true, '1 action', '60 feet', '/api/spells/unseen-servant'),
('Flaming Sphere', 2, 'Up to 1 minute', false, '1 action', '60 feet', '/api/spells/flaming-sphere'),
('Wall of Thorns', 6, 'Up to 10 minutes', false, '1 action', '120 feet', '/api/spells/wall-of-thorns'),
('Vampiric Touch', 3, 'Up to 1 minute', false, '1 action', 'Self', '/api/spells/vampiric-touch'),
('Hellish Rebuke', 1, 'Instantaneous', false, '1 reaction', '60 feet', '/api/spells/hellish-rebuke'),
('Magic Missile', 1, 'Instantaneous', false, '1 action', '120 feet', '/api/spells/magic-missile'),
('Sunbeam', 6, 'Up to 1 minute', false, '1 action', 'Self', '/api/spells/sunbeam'),
('Purify Food and Drink', 1, 'Instantaneous', true, '1 action', '10 feet', '/api/spells/purify-food-and-drink'),
('Antilife Shell', 5, 'Up to 1 hour', false, '1 action', 'Self', '/api/spells/antilife-shell'),
('Blindness/Deafness', 2, '1 minute', false, '1 action', '30 feet', '/api/spells/blindness-deafness'),
('True Strike', 0, 'Up to 1 round', false, '1 action', '30 feet', '/api/spells/true-strike'),
('Flame Strike', 5, 'Instantaneous', false, '1 action', '60 feet', '/api/spells/flame-strike'),
('Create or Destroy Water', 1, 'Instantaneous', false, '1 action', '30 feet', '/api/spells/create-or-destroy-water'),
('Gust of Wind', 2, 'Up to 1 minute', false, '1 action', 'Self', '/api/spells/gust-of-wind'),
('Call Lightning', 3, 'Up to 10 minutes', false, '1 action', '120 feet', '/api/spells/call-lightning'),
('Suggestion', 2, 'Up to 8 hours', false, '1 action', '30 feet', '/api/spells/suggestion'),
('Thunderwave', 1, 'Instantaneous', false, '1 action', 'Self', '/api/spells/thunderwave'),
('Blink', 3, '1 minute', false, '1 action', 'Self', '/api/spells/blink'),
('Hold Monster', 5, 'Up to 1 minute', false, '1 action', '90 feet', '/api/spells/hold-monster'),
('Glyph of Warding', 3, 'Until dispelled', false, '1 hour', 'Touch', '/api/spells/glyph-of-warding'),
('Globe of Invulnerability', 6, 'Up to 1 minute', false, '1 action', 'Self', '/api/spells/globe-of-invulnerability'),
('Bless', 1, 'Up to 1 minute', false, '1 action', '30 feet', '/api/spells/bless'),
('Telepathic Bond', 5, '1 hour', true, '1 action', '30 feet', '/api/spells/telepathic-bond'),
('Flesh to Stone', 6, 'Up to 1 minute', false, '1 action', '60 feet', '/api/spells/flesh-to-stone'),
('Shapechange', 9, 'Up to 1 hour', false, '1 action', 'Self', '/api/spells/shapechange'),
('Symbol', 7, 'Until dispelled', false, '1 minute', 'Touch', '/api/spells/symbol'),
('Grease', 1, '1 minute', false, '1 action', '60 feet', '/api/spells/grease'),
('Hypnotic Pattern', 3, 'Up to 1 minute', false, '1 action', '120 feet', '/api/spells/hypnotic-pattern'),
('Locate Creature', 4, 'Up to 1 hour', false, '1 action', 'Self', '/api/spells/locate-creature'),
('Mass Suggestion', 6, '24 hours', false, '1 action', '60 feet', '/api/spells/mass-suggestion'),
('Burning Hands', 1, 'Instantaneous', false, '1 action', 'Self', '/api/spells/burning-hands'),
('Identify', 1, 'Instantaneous', true, '1 minute', 'Touch', '/api/spells/identify'),
('Guards and Wards', 6, '24 hours', false, '10 minutes', 'Touch', '/api/spells/guards-and-wards'),
('Phantom Steed', 3, '1 hour', true, '1 minute', '30 feet', '/api/spells/phantom-steed'),
('Magnificent Mansion', 7, '24 hours', false, '1 minute', '300 feet', '/api/spells/magnificent-mansion'),
('Teleportation Circle', 5, '1 round', false, '1 minute', '10 feet', '/api/spells/teleportation-circle'),
('Wind Wall', 3, 'Up to 1 minute', false, '1 action', '120 feet', '/api/spells/wind-wall'),
('Invisibility', 2, 'Up to 1 hour', false, '1 action', 'Touch', '/api/spells/invisibility'),
('Heroism', 1, 'Up to 1 minute', false, '1 action', 'Touch', '/api/spells/heroism'),
('Mind Blank', 8, '24 hours', false, '1 action', 'Touch', '/api/spells/mind-blank'),
('Mass Heal', 9, 'Instantaneous', false, '1 action', '60 feet', '/api/spells/mass-heal'),
('Secret Chest', 4, 'Instantaneous', false, '1 action', 'Touch', '/api/spells/secret-chest'),
('Knock', 2, 'Instantaneous', false, '1 action', '60 feet', '/api/spells/knock'),
('Bestow Curse', 3, 'Up to 1 minute', false, '1 action', 'Touch', '/api/spells/bestow-curse'),
('Animate Objects', 5, 'Up to 1 minute', false, '1 action', '120 feet', '/api/spells/animate-objects'),
('Blur', 2, 'Up to 1 minute', false, '1 action', 'Self', '/api/spells/blur'),
('Bane', 1, 'Up to 1 minute', false, '1 action', '30 feet', '/api/spells/bane'),
('Continual Flame', 2, 'Until dispelled', false, '1 action', 'Touch', '/api/spells/continual-flame'),
('Power Word Stun', 8, 'Instantaneous', false, '1 action', '60 feet', '/api/spells/power-word-stun'),
('Awaken', 5, 'Instantaneous', false, '8 hours', 'Touch', '/api/spells/awaken'),
('Create Undead', 6, 'Instantaneous', false, '1 minute', '10 feet', '/api/spells/create-undead'),
('Dominate Beast', 4, 'Up to 1 minute', false, '1 action', '60 feet', '/api/spells/dominate-beast'),
('True Seeing', 6, '1 hour', false, '1 action', 'Touch', '/api/spells/true-seeing'),
('Counterspell', 3, 'Instantaneous', false, '1 reaction', '60 feet', '/api/spells/counterspell'),
('Tiny Hut', 3, '8 hours', true, '1 minute', 'Self', '/api/spells/tiny-hut'),
('Time Stop', 9, 'Instantaneous', false, '1 action', 'Self', '/api/spells/time-stop'),
('Healing Word', 1, 'Instantaneous', false, '1 bonus action', '60 feet', '/api/spells/healing-word'),
('Dominate Monster', 8, 'Up to 1 hour', false, '1 action', '60 feet', '/api/spells/dominate-monster'),
('Enlarge/Reduce', 2, 'Up to 1 minute', false, '1 action', '30 feet', '/api/spells/enlarge-reduce'),
('Holy Aura', 8, 'Up to 1 minute', false, '1 action', 'Self', '/api/spells/holy-aura'),
('Astral Projection', 9, 'Special', false, '1 hour', '10 feet', '/api/spells/astral-projection'),
('Heat Metal', 2, 'Up to 1 minute', false, '1 action', '60 feet', '/api/spells/heat-metal'),
('Arcane Hand', 5, 'Up to 1 minute', false, '1 action', '120 feet', '/api/spells/arcane-hand'),
('Dream', 5, '8 hours', false, '1 minute', 'Special', '/api/spells/dream'),
('Stone Shape', 4, 'Instantaneous', false, '1 action', 'Touch', '/api/spells/stone-shape'),
('Darkvision', 2, '8 hours', false, '1 action', 'Touch', '/api/spells/darkvision'),
('Divine Word', 7, 'Instantaneous', false, '1 bonus action', '30 feet', '/api/spells/divine-word'),
('Detect Thoughts', 2, 'Up to 1 minute', false, '1 action', 'Self', '/api/spells/detect-thoughts'),
('Control Water', 4, 'Up to 10 minutes', false, '1 action', '300 feet', '/api/spells/control-water'),
('Lightning Bolt', 3, 'Instantaneous', false, '1 action', 'Self', '/api/spells/lightning-bolt'),
('Geas', 5, '30 days', false, '1 minute', '60 feet', '/api/spells/geas'),
('Fireball', 3, 'Instantaneous', false, '1 action', '150 feet', '/api/spells/fireball'),
('Simulacrum', 7, 'Until dispelled', false, '12 hours', 'Touch', '/api/spells/simulacrum'),
('Rope Trick', 2, '1 hour', false, '1 action', 'Touch', '/api/spells/rope-trick'),
('Banishment', 4, 'Up to 1 minute', false, '1 action', '60 feet', '/api/spells/banishment'),
('Magic Mouth', 2, 'Until dispelled', true, '1 minute', '30 feet', '/api/spells/magic-mouth'),
('Hideous Laughter', 1, 'Up to 1 minute', false, '1 action', '30 feet', '/api/spells/hideous-laughter'),
('Comprehend Languages', 1, '1 hour', true, '1 action', 'Self', '/api/spells/comprehend-languages'),
('Spike Growth', 2, 'Up to 10 minutes', false, '1 action', '150 feet', '/api/spells/spike-growth'),
('Clairvoyance', 3, 'Up to 10 minutes', false, '10 minutes', '1 mile', '/api/spells/clairvoyance'),
('Imprisonment', 9, 'Until dispelled', false, '1 minute', '30 feet', '/api/spells/imprisonment'),
('Word of Recall', 6, 'Instantaneous', false, '1 action', '5 feet', '/api/spells/word-of-recall'),
('Shield of Faith', 1, 'Up to 10 minutes', false, '1 bonus action', '60 feet', '/api/spells/shield-of-faith'),
('Sequester', 7, 'Until dispelled', false, '1 action', 'Touch', '/api/spells/sequester'),
('Spider Climb', 2, 'Up to 1 hour', false, '1 action', 'Touch', '/api/spells/spider-climb'),
('Guidance', 0, 'Up to 1 minute', false, '1 action', 'Touch', '/api/spells/guidance'),
('Water Breathing', 3, '24 hours', true, '1 action', '30 feet', '/api/spells/water-breathing'),
('Warding Bond', 2, '1 hour', false, '1 action', 'Touch', '/api/spells/warding-bond'),
('Zone of Truth', 2, '10 minutes', false, '1 action', '60 feet', '/api/spells/zone-of-truth'),
('Hallucinatory Terrain', 4, '24 hours', false, '10 minutes', '300 feet', '/api/spells/hallucinatory-terrain'),
('Project Image', 7, 'Up to 24 hours', false, '1 action', '500 miles', '/api/spells/project-image'),
('Glibness', 8, '1 hour', false, '1 action', 'Self', '/api/spells/glibness'),
('Finger of Death', 7, 'Instantaneous', false, '1 action', '60 feet', '/api/spells/finger-of-death'),
('Clone', 8, 'Instantaneous', false, '1 hour', 'Touch', '/api/spells/clone'),
('Detect Poison and Disease', 1, 'Up to 10 minutes', true, '1 action', 'Self', '/api/spells/detect-poison-and-disease'),
('Prismatic Spray', 7, 'Instantaneous', false, '1 action', 'Self', '/api/spells/prismatic-spray'),
('Sanctuary', 1, '1 minute', false, '1 bonus action', '30 feet', '/api/spells/sanctuary'),
('Resistance', 0, 'Up to 1 minute', false, '1 action', 'Touch', '/api/spells/resistance'),
('Teleport', 7, 'Instantaneous', false, '1 action', '10 feet', '/api/spells/teleport'),
('Protection from Poison', 2, '1 hour', false, '1 action', 'Touch', '/api/spells/protection-from-poison'),
('Reverse Gravity', 7, 'Up to 1 minute', false, '1 action', '100 feet', '/api/spells/reverse-gravity'),
('Commune with Nature', 5, 'Instantaneous', true, '1 minute', 'Self', '/api/spells/commune-with-nature'),
('Water Walk', 3, '1 hour', true, '1 action', '30 feet', '/api/spells/water-walk'),
('Reincarnate', 5, 'Instantaneous', false, '1 hour', 'Touch', '/api/spells/reincarnate'),
('Weird', 9, 'Up to 1 minute', false, '1 action', '120 feet', '/api/spells/weird'),
('Gate', 9, 'Up to 1 minute', false, '1 action', '60 feet', '/api/spells/gate'),
('Spiritual Weapon', 2, '1 minute', false, '1 bonus action', '60 feet', '/api/spells/spiritual-weapon'),
('Silent Image', 1, 'Up to 10 minutes', false, '1 action', '60 feet', '/api/spells/silent-image'),
('Compulsion', 4, 'Up to 1 minute', false, '1 action', '30 feet', '/api/spells/compulsion'),
('Alarm', 1, '8 hours', true, '1 minute', '30 feet', '/api/spells/alarm'),
('Commune', 5, '1 minute', true, '1 minute', 'Self', '/api/spells/commune'),
('Create Food and Water', 3, 'Instantaneous', false, '1 action', '30 feet', '/api/spells/create-food-and-water'),
('Hunter''s Mark', 1, 'Up to 1 hour', false, '1 bonus action', '90 feet', '/api/spells/hunters-mark'),
('Move Earth', 6, 'Up to 2 hours', false, '1 action', '120 feet', '/api/spells/move-earth'),
('Insect Plague', 5, 'Up to 10 minutes', false, '1 action', '300 feet', '/api/spells/insect-plague'),
('Circle of Death', 6, 'Instantaneous', false, '1 action', '150 feet', '/api/spells/circle-of-death'),
('Misty Step', 2, 'Instantaneous', false, '1 bonus action', 'Self', '/api/spells/misty-step'),
('Longstrider', 1, '1 hour', false, '1 action', 'Touch', '/api/spells/longstrider'),
('Magic Circle', 3, '1 hour', false, '1 minute', '10 feet', '/api/spells/magic-circle'),
('Remove Curse', 3, 'Instantaneous', false, '1 action', 'Touch', '/api/spells/remove-curse'),
('Dispel Magic', 3, 'Instantaneous', false, '1 action', '120 feet', '/api/spells/dispel-magic'),
('Flame Blade', 2, 'Up to 10 minutes', false, '1 bonus action', 'Self', '/api/spells/flame-blade'),
('Planar Ally', 6, 'Instantaneous', false, '10 minutes', '60 feet', '/api/spells/planar-ally'),
('Ray of Frost', 0, 'Instantaneous', false, '1 action', '60 feet', '/api/spells/ray-of-frost'),
('Locate Object', 2, 'Up to 10 minutes', false, '1 action', 'Self', '/api/spells/locate-object'),
('Stoneskin', 4, 'Up to 1 hour', false, '1 action', 'Touch', '/api/spells/stoneskin'),
('Sleep', 1, '1 minute', false, '1 action', '90 feet', '/api/spells/sleep'),
('Greater Restoration', 5, 'Instantaneous', false, '1 action', 'Touch', '/api/spells/greater-restoration'),
('Shatter', 2, 'Instantaneous', false, '1 action', '60 feet', '/api/spells/shatter'),
('Conjure Celestial', 7, 'Up to 1 hour', false, '1 minute', '90 feet', '/api/spells/conjure-celestial'),
('Speak with Plants', 3, '10 minutes', false, '1 action', 'Self', '/api/spells/speak-with-plants'),
('Silence', 2, 'Up to 10 minutes', true, '1 action', '120 feet', '/api/spells/silence'),
('Slow', 3, 'Up to 1 minute', false, '1 action', '120 feet', '/api/spells/slow'),
('Eyebite', 6, 'Up to 1 minute', false, '1 action', 'Self', '/api/spells/eyebite'),
('Disguise Self', 1, '1 hour', false, '1 action', 'Self', '/api/spells/disguise-self'),
('Telekinesis', 5, 'Up to 10 minutes', false, '1 action', '60 feet', '/api/spells/telekinesis'),
('Confusion', 4, 'Up to 1 minute', false, '1 action', '90 feet', '/api/spells/confusion'),
('Divine Favor', 1, 'Up to 1 minute', false, '1 bonus action', 'Self', '/api/spells/divine-favor'),
('Daylight', 3, '1 hour', false, '1 action', '60 feet', '/api/spells/daylight'),
('Contingency', 6, '10 days', false, '10 minutes', 'Self', '/api/spells/contingency'),
('Arcane Sword', 7, 'Up to 1 minute', false, '1 action', '60 feet', '/api/spells/arcane-sword'),
('Aid', 2, '8 hours', false, '1 action', '30 feet', '/api/spells/aid'),
('Command', 1, '1 round', false, '1 action', '60 feet', '/api/spells/command'),
('Freedom of Movement', 4, '1 hour', false, '1 action', 'Touch', '/api/spells/freedom-of-movement'),
('Instant Summons', 6, 'Until dispelled', true, '1 minute', 'Touch', '/api/spells/instant-summons'),
('Planar Binding', 5, '24 hours', false, '1 hour', '60 feet', '/api/spells/planar-binding'),
('Irresistible Dance', 6, 'Up to 1 minute', false, '1 action', '30 feet', '/api/spells/irresistible-dance'),
('Conjure Fey', 6, 'Up to 1 hour', false, '1 minute', '90 feet', '/api/spells/conjure-fey'),
('Inflict Wounds', 1, 'Instantaneous', false, '1 action', 'Touch', '/api/spells/inflict-wounds'),
('Mage Hand', 0, '1 minute', false, '1 action', '30 feet', '/api/spells/mage-hand'),
('Lesser Restoration', 2, 'Instantaneous', false, '1 action', 'Touch', '/api/spells/lesser-restoration'),
('Locate Animals or Plants', 2, 'Instantaneous', true, '1 action', 'Self', '/api/spells/locate-animals-or-plants'),
('Mage Armor', 1, '8 hours', false, '1 action', 'Touch', '/api/spells/mage-armor'),
('Spare the Dying', 0, 'Instantaneous', false, '1 action', 'Touch', '/api/spells/spare-the-dying'),
('Black Tentacles', 4, 'Up to 1 minute', false, '1 action', '90 feet', '/api/spells/black-tentacles'),
('Mass Healing Word', 3, 'Instantaneous', false, '1 bonus action', '60 feet', '/api/spells/mass-healing-word'),
('Incendiary Cloud', 8, 'Up to 1 minute', false, '1 action', '150 feet', '/api/spells/incendiary-cloud'),
('Mirage Arcane', 7, '10 days', false, '10 minutes', 'Sight', '/api/spells/mirage-arcane'),
('Maze', 8, 'Up to 10 minutes', false, '1 action', '60 feet', '/api/spells/maze'),
('Foresight', 9, '8 hours', false, '1 minute', 'Touch', '/api/spells/foresight'),
('Stinking Cloud', 3, 'Up to 1 minute', false, '1 action', '90 feet', '/api/spells/stinking-cloud'),
('Acid Splash', 0, 'Instantaneous', false, '1 action', '60 feet', '/api/spells/acid-splash'),
('Legend Lore', 5, 'Instantaneous', false, '10 minutes', 'Self', '/api/spells/legend-lore'),
('Mending', 0, 'Instantaneous', false, '1 minute', 'Touch', '/api/spells/mending'),
('Branding Smite', 2, 'Up to 1 minute', false, '1 bonus action', 'Self', '/api/spells/branding-smite'),
('Levitate', 2, 'Up to 10 minutes', false, '1 action', '60 feet', '/api/spells/levitate'),
('Thaumaturgy', 0, '1 minute', false, '1 action', '30 feet', '/api/spells/thaumaturgy'),
('Tongues', 3, '1 hour', false, '1 action', 'Touch', '/api/spells/tongues'),
('Shillelagh', 0, '1 minute', false, '1 bonus action', 'Touch', '/api/spells/shillelagh'),
('Seeming', 5, '8 hours', false, '1 action', '30 feet', '/api/spells/seeming'),
('Sending', 3, '1 round', false, '1 action', 'Unlimited', '/api/spells/sending'),
('Goodberry', 1, 'Instantaneous', false, '1 action', 'Touch', '/api/spells/goodberry'),
('Detect Magic', 1, 'Up to 10 minutes', true, '1 action', 'Self', '/api/spells/detect-magic'),
('Poison Spray', 0, 'Instantaneous', false, '1 action', '10 feet', '/api/spells/poison-spray'),
('Heal', 6, 'Instantaneous', false, '1 action', '60 feet', '/api/spells/heal'),
('Greater Invisibility', 4, 'Up to 1 minute', false, '1 action', 'Touch', '/api/spells/greater-invisibility'),
('Forbiddance', 6, '24 hours', true, '10 minutes', 'Touch', '/api/spells/forbiddance'),
('Harm', 6, 'Instantaneous', false, '1 action', '60 feet', '/api/spells/harm'),
('Forcecage', 7, '1 hour', false, '1 action', '100 feet', '/api/spells/forcecage'),
('Haste', 3, 'Up to 1 minute', false, '1 action', '30 feet', '/api/spells/haste'),
('Guiding Bolt', 1, '1 round', false, '1 action', '120 feet', '/api/spells/guiding-bolt'),
('Detect Evil and Good', 1, 'Up to 10 minutes', false, '1 action', 'Self', '/api/spells/detect-evil-and-good'),
('Creation', 5, 'Special', false, '1 minute', '30 feet', '/api/spells/creation'),
('Divination', 4, 'Instantaneous', true, '1 action', 'Self', '/api/spells/divination'),
('Enthrall', 2, '1 minute', false, '1 action', '60 feet', '/api/spells/enthrall'),
('Eldritch Blast', 0, 'Instantaneous', false, '1 action', '120 feet', '/api/spells/eldritch-blast'),
('Nondetection', 3, '8 hours', false, '1 action', 'Touch', '/api/spells/nondetection'),
('Dominate Person', 5, 'Up to 1 minute', false, '1 action', '60 feet', '/api/spells/dominate-person'),
('Earthquake', 8, 'Up to 1 minute', false, '1 action', '500 feet', '/api/spells/earthquake'),
('Ice Storm', 4, 'Instantaneous', false, '1 action', '300 feet', '/api/spells/ice-storm'),
('Dancing Lights', 0, 'Up to 1 minute', false, '1 action', '120 feet', '/api/spells/dancing-lights'),
('Animate Dead', 3, 'Instantaneous', false, '1 minute', '10 feet', '/api/spells/animate-dead'),
('Ray of Enfeeblement', 2, 'Up to 1 minute', false, '1 action', '60 feet', '/api/spells/ray-of-enfeeblement'),
('Demiplane', 8, '1 hour', false, '1 action', '60 feet', '/api/spells/demiplane'),
('Raise Dead', 5, 'Instantaneous', false, '1 hour', 'Touch', '/api/spells/raise-dead'),
('Faithful Hound', 4, '8 hours', false, '1 action', '30 feet', '/api/spells/faithful-hound'),
('Death Ward', 4, '8 hours', false, '1 action', 'Touch', '/api/spells/death-ward'),
('Entangle', 1, 'Up to 1 minute', false, '1 action', '90 feet', '/api/spells/entangle'),
('Fabricate', 4, 'Instantaneous', false, '10 minutes', '120 feet', '/api/spells/fabricate'),
('Faerie Fire', 1, 'Up to 1 minute', false, '1 action', '60 feet', '/api/spells/faerie-fire'),
('Etherealness', 7, '8 hours', false, '1 action', 'Self', '/api/spells/etherealness'),
('Hallow', 5, 'Until dispelled', false, '24 hours', 'Touch', '/api/spells/hallow'),
('Fog Cloud', 1, 'Up to 1 hour', false, '1 action', '120 feet', '/api/spells/fog-cloud'),
('Major Image', 3, 'Up to 10 minutes', false, '1 action', '120 feet', '/api/spells/major-image'),
('Guardian of Faith', 4, '8 hours', false, '1 action', '30 feet', '/api/spells/guardian-of-faith'),
('Delayed Blast Fireball', 7, 'Up to 1 minute', false, '1 action', '150 feet', '/api/spells/delayed-blast-fireball'),
('Heroes'' Feast', 6, 'Instantaneous', false, '10 minutes', '30 feet', '/api/spells/heroes-feast'),
('Storm of Vengeance', 9, 'Up to 1 minute', false, '1 action', 'Sight', '/api/spells/storm-of-vengeance'),
('Contagion', 5, '7 days', false, '1 action', 'Touch', '/api/spells/contagion'),
('Prismatic Wall', 9, '10 minutes', false, '1 action', '60 feet', '/api/spells/prismatic-wall'),
('Alter Self', 2, 'Up to 1 hour', false, '1 action', 'Self', '/api/spells/alter-self'),
('Animal Friendship', 1, '24 hours', false, '1 action', '30 feet', '/api/spells/animal-friendship'),
('Shocking Grasp', 0, 'Instantaneous', false, '1 action', 'Touch', '/api/spells/shocking-grasp'),
('Expeditious Retreat', 1, 'Up to 10 minutes', false, '1 bonus action', 'Self', '/api/spells/expeditious-retreat'),
('Produce Flame', 0, '10 minutes', false, '1 action', 'Self', '/api/spells/produce-flame'),
('Disintegrate', 6, 'Instantaneous', false, '1 action', '60 feet', '/api/spells/disintegrate'),
('Find Traps', 2, 'Instantaneous', false, '1 action', '120 feet', '/api/spells/find-traps'),
('Animal Shapes', 8, 'Up to 24 hours', false, '1 action', '30 feet', '/api/spells/animal-shapes'),
('Resurrection', 7, 'Instantaneous', false, '1 hour', 'Touch', '/api/spells/resurrection'),
('Minor Illusion', 0, '1 minute', false, '1 action', '30 feet', '/api/spells/minor-illusion'),
('Modify Memory', 5, 'Up to 1 minute', false, '1 action', '30 feet', '/api/spells/modify-memory'),
('Web', 2, 'Up to 1 hour', false, '1 action', '60 feet', '/api/spells/web'),
('Mirror Image', 2, '1 minute', false, '1 action', 'Self', '/api/spells/mirror-image'),
('Giant Insect', 4, 'Up to 10 minutes', false, '1 action', '30 feet', '/api/spells/giant-insect'),
('Gentle Repose', 2, '10 days', true, '1 action', 'Touch', '/api/spells/gentle-repose'),
('Meld into Stone', 3, '8 hours', true, '1 action', 'Touch', '/api/spells/meld-into-stone'),
('Floating Disk', 1, '1 hour', true, '1 action', '30 feet', '/api/spells/floating-disk'),
('Moonbeam', 2, 'Up to 1 minute', false, '1 action', '120 feet', '/api/spells/moonbeam'),
('Fire Storm', 7, 'Instantaneous', false, '1 action', '150 feet', '/api/spells/fire-storm'),
('Illusory Script', 1, '10 days', true, '1 minute', 'Touch', '/api/spells/illusory-script'),
('Chain Lightning', 6, 'Instantaneous', false, '1 action', '150 feet', '/api/spells/chain-lightning'),
('Pass without Trace', 2, 'Up to 1 hour', false, '1 action', 'Self', '/api/spells/pass-without-trace'),
('Jump', 1, '1 minute', false, '1 action', 'Touch', '/api/spells/jump'),
('Fly', 3, 'Up to 10 minutes', false, '1 action', 'Touch', '/api/spells/fly'),
('Light', 0, '1 hour', false, '1 action', 'Touch', '/api/spells/light'),
('Phantasmal Killer', 4, 'Up to 1 minute', false, '1 action', '120 feet', '/api/spells/phantasmal-killer'),
('Gaseous Form', 3, 'Up to 1 hour', false, '1 action', 'Touch', '/api/spells/gaseous-form'),
('Charm Person', 1, '1 hour', false, '1 action', '30 feet', '/api/spells/charm-person'),
('Spirit Guardians', 3, 'Up to 10 minutes', false, '1 action', 'Self', '/api/spells/spirit-guardians'),
('Speak with Dead', 3, '10 minutes', false, '1 action', '10 feet', '/api/spells/speak-with-dead');