INSERT INTO Spells
    (name, spell_level, duration, is_ritual, casting_time, range, api_link)
VALUES
    ("Produce Flame", 0, "10 minutes", false, "1 action", "Self", "/api/spells/produce-flame"),
("Animate Dead", 3, "Instantaneous", false, "1 minute", "10 feet", "/api/spells/animate-dead"),
("Barkskin", 2, "Up to 1 hour", false, "1 action", "Touch", "/api/spells/barkskin"),
("Magic Missile", 1, "Instantaneous", false, "1 action", "120 feet", "/api/spells/magic-missile"),
("Conjure Minor Elementals", 4, "Up to 1 hour", false, "1 minute", "90 feet", "/api/spells/conjure-minor-elementals"),
("Disintegrate", 6, "Instantaneous", false, "1 action", "60 feet", "/api/spells/disintegrate"),
("Arcane Eye", 4, "Up to 1 hour", false, "1 action", "30 feet", "/api/spells/arcane-eye"),
("Divination", 4, "Instantaneous", true, "1 action", "Self", "/api/spells/divination"),
("Antilife Shell", 5, "Up to 1 hour", false, "1 action", "Self", "/api/spells/antilife-shell"),
("Acid Arrow", 2, "Instantaneous", false, "1 action", "90 feet", "/api/spells/acid-arrow"),
("Glyph of Warding", 3, "Until dispelled", false, "1 hour", "Touch", "/api/spells/glyph-of-warding"),
("Dream", 5, "8 hours", false, "1 minute", "Special", "/api/spells/dream"),
("Gaseous Form", 3, "Up to 1 hour", false, "1 action", "Touch", "/api/spells/gaseous-form"),
("Greater Restoration", 5, "Instantaneous", false, "1 action", "Touch", "/api/spells/greater-restoration"),
("Fabricate", 4, "Instantaneous", false, "10 minutes", "120 feet", "/api/spells/fabricate"),
("Expeditious Retreat", 1, "Up to 10 minutes", false, "1 bonus action", "Self", "/api/spells/expeditious-retreat"),
("Acid Splash", 0, "Instantaneous", false, "1 action", "60 feet", "/api/spells/acid-splash"),
("Dispel Magic", 3, "Instantaneous", false, "1 action", "120 feet", "/api/spells/dispel-magic"),
("Mass Cure Wounds", 5, "Instantaneous", false, "1 action", "60 feet", "/api/spells/mass-cure-wounds"),
("Aid", 2, "8 hours", false, "1 action", "30 feet", "/api/spells/aid"),
("Power Word Kill", 9, "Instantaneous", false, "1 action", "60 feet", "/api/spells/power-word-kill"),
("Sleep", 1, "1 minute", false, "1 action", "90 feet", "/api/spells/sleep"),
("Faerie Fire", 1, "Up to 1 minute", false, "1 action", "60 feet", "/api/spells/faerie-fire"),
("Contingency", 6, "10 days", false, "10 minutes", "Self", "/api/spells/contingency"),
("Illusory Script", 1, "10 days", true, "1 minute", "Touch", "/api/spells/illusory-script"),
("Mage Hand", 0, "1 minute", false, "1 action", "30 feet", "/api/spells/mage-hand"),
("False Life", 1, "1 hour", false, "1 action", "Self", "/api/spells/false-life"),
("Animal Messenger", 2, "24 hours", true, "1 action", "30 feet", "/api/spells/animal-messenger"),
("Detect Evil and Good", 1, "Up to 10 minutes", false, "1 action", "Self", "/api/spells/detect-evil-and-good"),
("Magic Weapon", 2, "Up to 1 hour", false, "1 bonus action", "Touch", "/api/spells/magic-weapon"),
("Spiritual Weapon", 2, "1 minute", false, "1 bonus action", "60 feet", "/api/spells/spiritual-weapon"),
("Prestidigitation", 0, "1 hour", false, "1 action", "10 feet", "/api/spells/prestidigitation"),
("Spare the Dying", 0, "Instantaneous", false, "1 action", "Touch", "/api/spells/spare-the-dying"),
("Thaumaturgy", 0, "1 minute", false, "1 action", "30 feet", "/api/spells/thaumaturgy"),
("Prayer of Healing", 2, "Instantaneous", false, "10 minutes", "30 feet", "/api/spells/prayer-of-healing"),
("Alter Self", 2, "Up to 1 hour", false, "1 action", "Self", "/api/spells/alter-self"),
("Comprehend Languages", 1, "1 hour", true, "1 action", "Self", "/api/spells/comprehend-languages"),
("Create Food and Water", 3, "Instantaneous", false, "1 action", "30 feet", "/api/spells/create-food-and-water"),
("Sunburst", 8, "Instantaneous", false, "1 action", "150 feet", "/api/spells/sunburst"),
("Arcane Sword", 7, "Up to 1 minute", false, "1 action", "60 feet", "/api/spells/arcane-sword"),
("Antipathy/Sympathy", 8, "10 days", false, "1 hour", "60 feet", "/api/spells/antipathy-sympathy"),
("Sequester", 7, "Until dispelled", false, "1 action", "Touch", "/api/spells/sequester"),
("Healing Word", 1, "Instantaneous", false, "1 bonus action", "60 feet", "/api/spells/healing-word"),
("Grease", 1, "1 minute", false, "1 action", "60 feet", "/api/spells/grease"),
("Telekinesis", 5, "Up to 10 minutes", false, "1 action", "60 feet", "/api/spells/telekinesis"),
("Imprisonment", 9, "Until dispelled", false, "1 minute", "30 feet", "/api/spells/imprisonment"),
("Create Undead", 6, "Instantaneous", false, "1 minute", "10 feet", "/api/spells/create-undead"),
("Conjure Woodland Beings", 4, "Up to 1 hour", false, "1 action", "60 feet", "/api/spells/conjure-woodland-beings"),
("Speak with Dead", 3, "10 minutes", false, "1 action", "10 feet", "/api/spells/speak-with-dead"),
("Color Spray", 1, "1 round", false, "1 action", "Self", "/api/spells/color-spray"),
("Geas", 5, "30 days", false, "1 minute", "60 feet", "/api/spells/geas"),
("Mirror Image", 2, "1 minute", false, "1 action", "Self", "/api/spells/mirror-image"),
("Delayed Blast Fireball", 7, "Up to 1 minute", false, "1 action", "150 feet", "/api/spells/delayed-blast-fireball"),
("Haste", 3, "Up to 1 minute", false, "1 action", "30 feet", "/api/spells/haste"),
("Minor Illusion", 0, "1 minute", false, "1 action", "30 feet", "/api/spells/minor-illusion"),
("Holy Aura", 8, "Up to 1 minute", false, "1 action", "Self", "/api/spells/holy-aura"),
("Glibness", 8, "1 hour", false, "1 action", "Self", "/api/spells/glibness"),
("Mislead", 5, "Up to 1 hour", false, "1 action", "Self", "/api/spells/mislead"),
("Flame Blade", 2, "Up to 10 minutes", false, "1 bonus action", "Self", "/api/spells/flame-blade"),
("Pass without Trace", 2, "Up to 1 hour", false, "1 action", "Self", "/api/spells/pass-without-trace"),
("Phantom Steed", 3, "1 hour", true, "1 minute", "30 feet", "/api/spells/phantom-steed"),
("Animal Shapes", 8, "Up to 24 hours", false, "1 action", "30 feet", "/api/spells/animal-shapes"),
("Insect Plague", 5, "Up to 10 minutes", false, "1 action", "300 feet", "/api/spells/insect-plague"),
("Project Image", 7, "Up to 24 hours", false, "1 action", "500 miles", "/api/spells/project-image"),
("Purify Food and Drink", 1, "Instantaneous", true, "1 action", "10 feet", "/api/spells/purify-food-and-drink"),
("Wall of Thorns", 6, "Up to 10 minutes", false, "1 action", "120 feet", "/api/spells/wall-of-thorns"),
("Plane Shift", 7, "Instantaneous", false, "1 action", "Touch", "/api/spells/plane-shift"),
("Poison Spray", 0, "Instantaneous", false, "1 action", "10 feet", "/api/spells/poison-spray"),
("Moonbeam", 2, "Up to 1 minute", false, "1 action", "120 feet", "/api/spells/moonbeam"),
("Plant Growth", 3, "Instantaneous", false, "1 action", "150 feet", "/api/spells/plant-growth"),
("Revivify", 3, "Instantaneous", false, "1 action", "Touch", "/api/spells/revivify"),
("Sacred Flame", 0, "Instantaneous", false, "1 action", "60 feet", "/api/spells/sacred-flame"),
("Tiny Hut", 3, "8 hours", true, "1 minute", "Self", "/api/spells/tiny-hut"),
("Zone of Truth", 2, "10 minutes", false, "1 action", "60 feet", "/api/spells/zone-of-truth"),
("Vampiric Touch", 3, "Up to 1 minute", false, "1 action", "Self", "/api/spells/vampiric-touch"),
("Forcecage", 7, "1 hour", false, "1 action", "100 feet", "/api/spells/forcecage"),
("Raise Dead", 5, "Instantaneous", false, "1 hour", "Touch", "/api/spells/raise-dead"),
("Wind Walk", 6, "8 hours", false, "1 minute", "30 feet", "/api/spells/wind-walk"),
("Alarm", 1, "8 hours", true, "1 minute", "30 feet", "/api/spells/alarm"),
("Animal Friendship", 1, "24 hours", false, "1 action", "30 feet", "/api/spells/animal-friendship"),
("Tongues", 3, "1 hour", false, "1 action", "Touch", "/api/spells/tongues"),
("Vicious Mockery", 0, "Instantaneous", false, "1 action", "60 feet", "/api/spells/vicious-mockery"),
("Reincarnate", 5, "Instantaneous", false, "1 hour", "Touch", "/api/spells/reincarnate"),
("Remove Curse", 3, "Instantaneous", false, "1 action", "Touch", "/api/spells/remove-curse"),
("Secret Chest", 4, "Instantaneous", false, "1 action", "Touch", "/api/spells/secret-chest"),
("Wish", 9, "Instantaneous", false, "1 action", "Self", "/api/spells/wish"),
("Weird", 9, "Up to 1 minute", false, "1 action", "120 feet", "/api/spells/weird"),
("Web", 2, "Up to 1 hour", false, "1 action", "60 feet", "/api/spells/web"),
("Resilient Sphere", 4, "Up to 1 minute", false, "1 action", "30 feet", "/api/spells/resilient-sphere"),
("True Seeing", 6, "1 hour", false, "1 action", "Touch", "/api/spells/true-seeing"),
("Wall of Force", 5, "Up to 10 minutes", false, "1 action", "120 feet", "/api/spells/wall-of-force"),
("Tree Stride", 5, "Up to 1 minute", false, "1 action", "Self", "/api/spells/tree-stride"),
("Magnificent Mansion", 7, "24 hours", false, "1 minute", "300 feet", "/api/spells/magnificent-mansion"),
("Mass Suggestion", 6, "24 hours", false, "1 action", "60 feet", "/api/spells/mass-suggestion"),
("Fog Cloud", 1, "Up to 1 hour", false, "1 action", "120 feet", "/api/spells/fog-cloud"),
("Warding Bond", 2, "1 hour", false, "1 action", "Touch", "/api/spells/warding-bond"),
("True Strike", 0, "Up to 1 round", false, "1 action", "30 feet", "/api/spells/true-strike"),
("Guards and Wards", 6, "24 hours", false, "10 minutes", "Touch", "/api/spells/guards-and-wards"),
("True Resurrection", 9, "Instantaneous", false, "1 hour", "Touch", "/api/spells/true-resurrection"),
("Shapechange", 9, "Up to 1 hour", false, "1 action", "Self", "/api/spells/shapechange"),
("Wall of Stone", 5, "Up to 10 minutes", false, "1 action", "120 feet", "/api/spells/wall-of-stone"),
("Hold Person", 2, "Up to 1 minute", false, "1 action", "60 feet", "/api/spells/hold-person"),
("Unseen Servant", 1, "1 hour", true, "1 action", "60 feet", "/api/spells/unseen-servant"),
("Scorching Ray", 2, "Instantaneous", false, "1 action", "120 feet", "/api/spells/scorching-ray"),
("See Invisibility", 2, "1 hour", false, "1 action", "Self", "/api/spells/see-invisibility"),
("Seeming", 5, "8 hours", false, "1 action", "30 feet", "/api/spells/seeming"),
("Scrying", 5, "Up to 10 minutes", false, "10 minutes", "Self", "/api/spells/scrying"),
("Eyebite", 6, "Up to 1 minute", false, "1 action", "Self", "/api/spells/eyebite"),
("Regenerate", 7, "1 hour", false, "1 minute", "Touch", "/api/spells/regenerate"),
("Sanctuary", 1, "1 minute", false, "1 bonus action", "30 feet", "/api/spells/sanctuary"),
("Wind Wall", 3, "Up to 1 minute", false, "1 action", "120 feet", "/api/spells/wind-wall"),
("Wall of Fire", 4, "Up to 1 minute", false, "1 action", "120 feet", "/api/spells/wall-of-fire"),
("Magic Circle", 3, "1 hour", false, "1 minute", "10 feet", "/api/spells/magic-circle"),
("Guiding Bolt", 1, "1 round", false, "1 action", "120 feet", "/api/spells/guiding-bolt"),
("Major Image", 3, "Up to 10 minutes", false, "1 action", "120 feet", "/api/spells/major-image"),
("Enlarge/Reduce", 2, "Up to 1 minute", false, "1 action", "30 feet", "/api/spells/enlarge-reduce"),
("Contact Other Plane", 5, "1 minute", true, "1 minute", "Self", "/api/spells/contact-other-plane"),
("Etherealness", 7, "8 hours", false, "1 action", "Self", "/api/spells/etherealness"),
("Hold Monster", 5, "Up to 1 minute", false, "1 action", "90 feet", "/api/spells/hold-monster"),
("Storm of Vengeance", 9, "Up to 1 minute", false, "1 action", "Sight", "/api/spells/storm-of-vengeance"),
("True Polymorph", 9, "Up to 1 hour", false, "1 action", "30 feet", "/api/spells/true-polymorph"),
("Mass Healing Word", 3, "Instantaneous", false, "1 bonus action", "60 feet", "/api/spells/mass-healing-word"),
("Wall of Ice", 6, "Up to 10 minutes", false, "1 action", "120 feet", "/api/spells/wall-of-ice"),
("Ray of Enfeeblement", 2, "Up to 1 minute", false, "1 action", "60 feet", "/api/spells/ray-of-enfeeblement"),
("Fly", 3, "Up to 10 minutes", false, "1 action", "Touch", "/api/spells/fly"),
("Faithful Hound", 4, "8 hours", false, "1 action", "30 feet", "/api/spells/faithful-hound"),
("Water Walk", 3, "1 hour", true, "1 action", "30 feet", "/api/spells/water-walk"),
("Foresight", 9, "8 hours", false, "1 minute", "Touch", "/api/spells/foresight"),
("Word of Recall", 6, "Instantaneous", false, "1 action", "5 feet", "/api/spells/word-of-recall"),
("Ice Storm", 4, "Instantaneous", false, "1 action", "300 feet", "/api/spells/ice-storm"),
("Telepathic Bond", 5, "1 hour", true, "1 action", "30 feet", "/api/spells/telepathic-bond"),
("Find Familiar", 1, "Instantaneous", true, "1 hour", "10 feet", "/api/spells/find-familiar"),
("Simulacrum", 7, "Until dispelled", false, "12 hours", "Touch", "/api/spells/simulacrum"),
("Speak with Animals", 1, "10 minutes", true, "1 action", "Self", "/api/spells/speak-with-animals"),
("Enhance Ability", 2, "Up to 1 hour", false, "1 action", "Touch", "/api/spells/enhance-ability"),
("Mass Heal", 9, "Instantaneous", false, "1 action", "60 feet", "/api/spells/mass-heal"),
("Druidcraft", 0, "Instantaneous", false, "1 action", "30 feet", "/api/spells/druidcraft"),
("Find Steed", 2, "Instantaneous", false, "10 minutes", "30 feet", "/api/spells/find-steed"),
("Entangle", 1, "Up to 1 minute", false, "1 action", "90 feet", "/api/spells/entangle"),
("Sunbeam", 6, "Up to 1 minute", false, "1 action", "Self", "/api/spells/sunbeam"),
("Slow", 3, "Up to 1 minute", false, "1 action", "120 feet", "/api/spells/slow"),
("Stone Shape", 4, "Instantaneous", false, "1 action", "Touch", "/api/spells/stone-shape"),
("Feather Fall", 1, "1 minute", false, "1 reaction", "60 feet", "/api/spells/feather-fall"),
("Darkness", 2, "Up to 10 minutes", false, "1 action", "60 feet", "/api/spells/darkness"),
("Speak with Plants", 3, "10 minutes", false, "1 action", "Self", "/api/spells/speak-with-plants"),
("Stinking Cloud", 3, "Up to 1 minute", false, "1 action", "90 feet", "/api/spells/stinking-cloud"),
("Cure Wounds", 1, "Instantaneous", false, "1 action", "Touch", "/api/spells/cure-wounds"),
("Daylight", 3, "1 hour", false, "1 action", "60 feet", "/api/spells/daylight"),
("Dispel Evil and Good", 5, "Up to 1 minute", false, "1 action", "Self", "/api/spells/dispel-evil-and-good"),
("Planar Binding", 5, "24 hours", false, "1 hour", "60 feet", "/api/spells/planar-binding"),
("Demiplane", 8, "1 hour", false, "1 action", "60 feet", "/api/spells/demiplane"),
("Darkvision", 2, "8 hours", false, "1 action", "Touch", "/api/spells/darkvision"),
("Dominate Beast", 4, "Up to 1 minute", false, "1 action", "60 feet", "/api/spells/dominate-beast"),
("Detect Magic", 1, "Up to 10 minutes", true, "1 action", "Self", "/api/spells/detect-magic"),
("Death Ward", 4, "8 hours", false, "1 action", "Touch", "/api/spells/death-ward"),
("Dominate Person", 5, "Up to 1 minute", false, "1 action", "60 feet", "/api/spells/dominate-person"),
("Spider Climb", 2, "Up to 1 hour", false, "1 action", "Touch", "/api/spells/spider-climb"),
("Meteor Swarm", 9, "Instantaneous", false, "1 action", "1 mile", "/api/spells/meteor-swarm"),
("Shillelagh", 0, "1 minute", false, "1 bonus action", "Touch", "/api/spells/shillelagh"),
("Longstrider", 1, "1 hour", false, "1 action", "Touch", "/api/spells/longstrider"),
("Jump", 1, "1 minute", false, "1 action", "Touch", "/api/spells/jump"),
("Locate Creature", 4, "Up to 1 hour", false, "1 action", "Self", "/api/spells/locate-creature"),
("Polymorph", 4, "Up to 1 hour", false, "1 action", "60 feet", "/api/spells/polymorph"),
("Mage Armor", 1, "8 hours", false, "1 action", "Touch", "/api/spells/mage-armor"),
("Silence", 2, "Up to 10 minutes", true, "1 action", "120 feet", "/api/spells/silence"),
("Silent Image", 1, "Up to 10 minutes", false, "1 action", "60 feet", "/api/spells/silent-image"),
("Mending", 0, "Instantaneous", false, "1 minute", "Touch", "/api/spells/mending"),
("Astral Projection", 9, "Special", false, "1 hour", "10 feet", "/api/spells/astral-projection"),
("Fire Bolt", 0, "Instantaneous", false, "1 action", "120 feet", "/api/spells/fire-bolt"),
("Knock", 2, "Instantaneous", false, "1 action", "60 feet", "/api/spells/knock"),
("Locate Object", 2, "Up to 10 minutes", false, "1 action", "Self", "/api/spells/locate-object"),
("Legend Lore", 5, "Instantaneous", false, "10 minutes", "Self", "/api/spells/legend-lore"),
("Reverse Gravity", 7, "Up to 1 minute", false, "1 action", "100 feet", "/api/spells/reverse-gravity"),
("Guardian of Faith", 4, "8 hours", false, "1 action", "30 feet", "/api/spells/guardian-of-faith"),
("Planar Ally", 6, "Instantaneous", false, "10 minutes", "60 feet", "/api/spells/planar-ally"),
("Transport via Plants", 6, "1 round", false, "1 action", "10 feet", "/api/spells/transport-via-plants"),
("Time Stop", 9, "Instantaneous", false, "1 action", "Self", "/api/spells/time-stop"),
("Shield", 1, "1 round", false, "1 reaction", "Self", "/api/spells/shield"),
("Resistance", 0, "Up to 1 minute", false, "1 action", "Touch", "/api/spells/resistance"),
("Phantasmal Killer", 4, "Up to 1 minute", false, "1 action", "120 feet", "/api/spells/phantasmal-killer"),
("Ray of Frost", 0, "Instantaneous", false, "1 action", "60 feet", "/api/spells/ray-of-frost"),
("Hallow", 5, "Until dispelled", false, "24 hours", "Touch", "/api/spells/hallow"),
("Protection from Poison", 2, "1 hour", false, "1 action", "Touch", "/api/spells/protection-from-poison"),
("Feeblemind", 8, "Instantaneous", false, "1 action", "150 feet", "/api/spells/feeblemind"),
("Misty Step", 2, "Instantaneous", false, "1 bonus action", "Self", "/api/spells/misty-step"),
("Continual Flame", 2, "Until dispelled", false, "1 action", "Touch", "/api/spells/continual-flame"),
("Flame Strike", 5, "Instantaneous", false, "1 action", "60 feet", "/api/spells/flame-strike"),
("Find the Path", 6, "Up to 24 hours", false, "1 minute", "Self", "/api/spells/find-the-path"),
("Flesh to Stone", 6, "Up to 1 minute", false, "1 action", "60 feet", "/api/spells/flesh-to-stone"),
("Irresistible Dance", 6, "Up to 1 minute", false, "1 action", "30 feet", "/api/spells/irresistible-dance"),
("Arcanist's Magic Aura", 2, "24 hours", false, "1 action", "Touch", "/api/spells/arcanists-magic-aura"),
("Shocking Grasp", 0, "Instantaneous", false, "1 action", "Touch", "/api/spells/shocking-grasp"),
("Stoneskin", 4, "Up to 1 hour", false, "1 action", "Touch", "/api/spells/stoneskin"),
("Fire Storm", 7, "Instantaneous", false, "1 action", "150 feet", "/api/spells/fire-storm"),
("Spirit Guardians", 3, "Up to 10 minutes", false, "1 action", "Self", "/api/spells/spirit-guardians"),
("Protection from Evil and Good", 1, "Up to 10 minutes", false, "1 action", "Touch", "/api/spells/protection-from-evil-and-good"),
("Teleport", 7, "Instantaneous", false, "1 action", "10 feet", "/api/spells/teleport"),
("Contagion", 5, "7 days", false, "1 action", "Touch", "/api/spells/contagion"),
("Dancing Lights", 0, "Up to 1 minute", false, "1 action", "120 feet", "/api/spells/dancing-lights"),
("Shatter", 2, "Instantaneous", false, "1 action", "60 feet", "/api/spells/shatter"),
("Sleet Storm", 3, "Up to 1 minute", false, "1 action", "150 feet", "/api/spells/sleet-storm"),
("Power Word Stun", 8, "Instantaneous", false, "1 action", "60 feet", "/api/spells/power-word-stun"),
("Hellish Rebuke", 1, "Instantaneous", false, "1 reaction", "60 feet", "/api/spells/hellish-rebuke"),
("Sending", 3, "1 round", false, "1 action", "Unlimited", "/api/spells/sending"),
("Suggestion", 2, "Up to 8 hours", false, "1 action", "30 feet", "/api/spells/suggestion"),
("Mind Blank", 8, "24 hours", false, "1 action", "Touch", "/api/spells/mind-blank"),
("Symbol", 7, "Until dispelled", false, "1 minute", "Touch", "/api/spells/symbol"),
("Burning Hands", 1, "Instantaneous", false, "1 action", "Self", "/api/spells/burning-hands"),
("Cone of Cold", 5, "Instantaneous", false, "1 action", "Self", "/api/spells/cone-of-cold"),
("Hypnotic Pattern", 3, "Up to 1 minute", false, "1 action", "120 feet", "/api/spells/hypnotic-pattern"),
("Identify", 1, "Instantaneous", true, "1 minute", "Touch", "/api/spells/identify"),
("Nondetection", 3, "8 hours", false, "1 action", "Touch", "/api/spells/nondetection"),
("Hunter's Mark", 1, "Up to 1 hour", false, "1 bonus action", "90 feet", "/api/spells/hunters-mark"),
("Teleportation Circle", 5, "1 round", false, "1 minute", "10 feet", "/api/spells/teleportation-circle"),
("Disguise Self", 1, "1 hour", false, "1 action", "Self", "/api/spells/disguise-self"),
("Confusion", 4, "Up to 1 minute", false, "1 action", "90 feet", "/api/spells/confusion"),
("Divine Word", 7, "Instantaneous", false, "1 bonus action", "30 feet", "/api/spells/divine-word"),
("Maze", 8, "Up to 10 minutes", false, "1 action", "60 feet", "/api/spells/maze"),
("Locate Animals or Plants", 2, "Instantaneous", true, "1 action", "Self", "/api/spells/locate-animals-or-plants"),
("Magic Jar", 6, "Until dispelled", false, "1 minute", "Self", "/api/spells/magic-jar"),
("Prismatic Spray", 7, "Instantaneous", false, "1 action", "Self", "/api/spells/prismatic-spray"),
("Flaming Sphere", 2, "Up to 1 minute", false, "1 action", "60 feet", "/api/spells/flaming-sphere"),
("Spike Growth", 2, "Up to 10 minutes", false, "1 action", "150 feet", "/api/spells/spike-growth"),
("Earthquake", 8, "Up to 1 minute", false, "1 action", "500 feet", "/api/spells/earthquake"),
("Protection from Energy", 3, "Up to 1 hour", false, "1 action", "Touch", "/api/spells/protection-from-energy"),
("Animate Objects", 5, "Up to 1 minute", false, "1 action", "120 feet", "/api/spells/animate-objects"),
("Gate", 9, "Up to 1 minute", false, "1 action", "60 feet", "/api/spells/gate"),
("Clone", 8, "Instantaneous", false, "1 hour", "Touch", "/api/spells/clone"),
("Commune with Nature", 5, "Instantaneous", true, "1 minute", "Self", "/api/spells/commune-with-nature"),
("Instant Summons", 6, "Until dispelled", true, "1 minute", "Touch", "/api/spells/instant-summons"),
("Finger of Death", 7, "Instantaneous", false, "1 action", "60 feet", "/api/spells/finger-of-death"),
("Prismatic Wall", 9, "10 minutes", false, "1 action", "60 feet", "/api/spells/prismatic-wall"),
("Forbiddance", 6, "24 hours", true, "10 minutes", "Touch", "/api/spells/forbiddance"),
("Globe of Invulnerability", 6, "Up to 1 minute", false, "1 action", "Self", "/api/spells/globe-of-invulnerability"),
("Dominate Monster", 8, "Up to 1 hour", false, "1 action", "60 feet", "/api/spells/dominate-monster"),
("Heal", 6, "Instantaneous", false, "1 action", "60 feet", "/api/spells/heal"),
("Greater Invisibility", 4, "Up to 1 minute", false, "1 action", "Touch", "/api/spells/greater-invisibility"),
("Gust of Wind", 2, "Up to 1 minute", false, "1 action", "Self", "/api/spells/gust-of-wind"),
("Magic Mouth", 2, "Until dispelled", true, "1 minute", "30 feet", "/api/spells/magic-mouth"),
("Blindness/Deafness", 2, "1 minute", false, "1 action", "30 feet", "/api/spells/blindness-deafness"),
("Water Breathing", 3, "24 hours", true, "1 action", "30 feet", "/api/spells/water-breathing"),
("Fire Shield", 4, "10 minutes", false, "1 action", "Self", "/api/spells/fire-shield"),
("Hideous Laughter", 1, "Up to 1 minute", false, "1 action", "30 feet", "/api/spells/hideous-laughter"),
("Inflict Wounds", 1, "Instantaneous", false, "1 action", "Touch", "/api/spells/inflict-wounds"),
("Eldritch Blast", 0, "Instantaneous", false, "1 action", "120 feet", "/api/spells/eldritch-blast"),
("Mirage Arcane", 7, "10 days", false, "10 minutes", "Sight", "/api/spells/mirage-arcane"),
("Rope Trick", 2, "1 hour", false, "1 action", "Touch", "/api/spells/rope-trick"),
("Counterspell", 3, "Instantaneous", false, "1 reaction", "60 feet", "/api/spells/counterspell"),
("Calm Emotions", 2, "Up to 1 minute", false, "1 action", "60 feet", "/api/spells/calm-emotions"),
("Blight", 4, "Instantaneous", false, "1 action", "30 feet", "/api/spells/blight"),
("Chill Touch", 0, "1 round", false, "1 action", "120 feet", "/api/spells/chill-touch"),
("Creation", 5, "Special", false, "1 minute", "30 feet", "/api/spells/creation"),
("Cloudkill", 5, "Up to 10 minutes", false, "1 action", "120 feet", "/api/spells/cloudkill"),
("Compulsion", 4, "Up to 1 minute", false, "1 action", "30 feet", "/api/spells/compulsion"),
("Commune", 5, "1 minute", true, "1 minute", "Self", "/api/spells/commune"),
("Charm Person", 1, "1 hour", false, "1 action", "30 feet", "/api/spells/charm-person"),
("Blade Barrier", 6, "Up to 10 minutes", false, "1 action", "90 feet", "/api/spells/blade-barrier"),
("Light", 0, "1 hour", false, "1 action", "Touch", "/api/spells/light"),
("Lightning Bolt", 3, "Instantaneous", false, "1 action", "Self", "/api/spells/lightning-bolt"),
("Modify Memory", 5, "Up to 1 minute", false, "1 action", "30 feet", "/api/spells/modify-memory"),
("Message", 0, "1 round", false, "1 action", "120 feet", "/api/spells/message"),
("Banishment", 4, "Up to 1 minute", false, "1 action", "60 feet", "/api/spells/banishment"),
("Lesser Restoration", 2, "Instantaneous", false, "1 action", "Touch", "/api/spells/lesser-restoration"),
("Passwall", 5, "1 hour", false, "1 action", "30 feet", "/api/spells/passwall"),
("Control Weather", 8, "Up to 8 hours", false, "10 minutes", "Self", "/api/spells/control-weather"),
("Conjure Elemental", 5, "Up to 1 hour", false, "1 minute", "90 feet", "/api/spells/conjure-elemental"),
("Shield of Faith", 1, "Up to 10 minutes", false, "1 bonus action", "60 feet", "/api/spells/shield-of-faith"),
("Resurrection", 7, "Instantaneous", false, "1 hour", "Touch", "/api/spells/resurrection"),
("Fear", 3, "Up to 1 minute", false, "1 action", "Self", "/api/spells/fear"),
("Incendiary Cloud", 8, "Up to 1 minute", false, "1 action", "150 feet", "/api/spells/incendiary-cloud"),
("Bane", 1, "Up to 1 minute", false, "1 action", "30 feet", "/api/spells/bane"),
("Arcane Hand", 5, "Up to 1 minute", false, "1 action", "120 feet", "/api/spells/arcane-hand"),
("Awaken", 5, "Instantaneous", false, "8 hours", "Touch", "/api/spells/awaken"),
("Detect Poison and Disease", 1, "Up to 10 minutes", true, "1 action", "Self", "/api/spells/detect-poison-and-disease"),
("Freezing Sphere", 6, "Instantaneous", false, "1 action", "300 feet", "/api/spells/freezing-sphere"),
("Heat Metal", 2, "Up to 1 minute", false, "1 action", "60 feet", "/api/spells/heat-metal"),
("Heroism", 1, "Up to 1 minute", false, "1 action", "Touch", "/api/spells/heroism"),
("Guidance", 0, "Up to 1 minute", false, "1 action", "Touch", "/api/spells/guidance"),
("Giant Insect", 4, "Up to 10 minutes", false, "1 action", "30 feet", "/api/spells/giant-insect"),
("Chain Lightning", 6, "Instantaneous", false, "1 action", "150 feet", "/api/spells/chain-lightning"),
("Thunderwave", 1, "Instantaneous", false, "1 action", "Self", "/api/spells/thunderwave"),
("Levitate", 2, "Up to 10 minutes", false, "1 action", "60 feet", "/api/spells/levitate"),
("Freedom of Movement", 4, "1 hour", false, "1 action", "Touch", "/api/spells/freedom-of-movement"),
("Goodberry", 1, "Instantaneous", false, "1 action", "Touch", "/api/spells/goodberry"),
("Hallucinatory Terrain", 4, "24 hours", false, "10 minutes", "300 feet", "/api/spells/hallucinatory-terrain"),
("Harm", 6, "Instantaneous", false, "1 action", "60 feet", "/api/spells/harm"),
("Dimension Door", 4, "Instantaneous", false, "1 action", "500 feet", "/api/spells/dimension-door"),
("Beacon of Hope", 3, "Up to 1 minute", false, "1 action", "30 feet", "/api/spells/beacon-of-hope"),
("Divine Favor", 1, "Up to 1 minute", false, "1 bonus action", "Self", "/api/spells/divine-favor"),
("Clairvoyance", 3, "Up to 10 minutes", false, "10 minutes", "1 mile", "/api/spells/clairvoyance"),
("Enthrall", 2, "1 minute", false, "1 action", "60 feet", "/api/spells/enthrall"),
("Blur", 2, "Up to 1 minute", false, "1 action", "Self", "/api/spells/blur"),
("Bless", 1, "Up to 1 minute", false, "1 action", "30 feet", "/api/spells/bless"),
("Create or Destroy Water", 1, "Instantaneous", false, "1 action", "30 feet", "/api/spells/create-or-destroy-water"),
("Bestow Curse", 3, "Up to 1 minute", false, "1 action", "Touch", "/api/spells/bestow-curse"),
("Black Tentacles", 4, "Up to 1 minute", false, "1 action", "90 feet", "/api/spells/black-tentacles"),
("Conjure Animals", 3, "Up to 1 hour", false, "1 action", "60 feet", "/api/spells/conjure-animals"),
("Arcane Lock", 2, "Until dispelled", false, "1 action", "Touch", "/api/spells/arcane-lock"),
("Control Water", 4, "Up to 10 minutes", false, "1 action", "300 feet", "/api/spells/control-water"),
("Branding Smite", 2, "Up to 1 minute", false, "1 bonus action", "Self", "/api/spells/branding-smite"),
("Detect Thoughts", 2, "Up to 1 minute", false, "1 action", "Self", "/api/spells/detect-thoughts"),
("Call Lightning", 3, "Up to 10 minutes", false, "1 action", "120 feet", "/api/spells/call-lightning"),
("Blink", 3, "1 minute", false, "1 action", "Self", "/api/spells/blink"),
("Augury", 2, "Instantaneous", true, "1 minute", "Self", "/api/spells/augury"),
("Move Earth", 6, "Up to 2 hours", false, "1 action", "120 feet", "/api/spells/move-earth"),
("Antimagic Field", 8, "Up to 1 hour", false, "1 action", "Self", "/api/spells/antimagic-field"),
("Conjure Celestial", 7, "Up to 1 hour", false, "1 minute", "90 feet", "/api/spells/conjure-celestial"),
("Private Sanctum", 4, "24 hours", false, "10 minutes", "120 feet", "/api/spells/private-sanctum"),
("Command", 1, "1 round", false, "1 action", "60 feet", "/api/spells/command"),
("Circle of Death", 6, "Instantaneous", false, "1 action", "150 feet", "/api/spells/circle-of-death"),
("Find Traps", 2, "Instantaneous", false, "1 action", "120 feet", "/api/spells/find-traps"),
("Heroes' Feast", 6, "Instantaneous", false, "10 minutes", "30 feet", "/api/spells/heroes-feast"),
("Fireball", 3, "Instantaneous", false, "1 action", "150 feet", "/api/spells/fireball"),
("Invisibility", 2, "Up to 1 hour", false, "1 action", "Touch", "/api/spells/invisibility"),
("Gentle Repose", 2, "10 days", true, "1 action", "Touch", "/api/spells/gentle-repose"),
("Floating Disk", 1, "1 hour", true, "1 action", "30 feet", "/api/spells/floating-disk"),
("Programmed Illusion", 6, "Until dispelled", false, "1 action", "120 feet", "/api/spells/programmed-illusion"),
("Meld into Stone", 3, "8 hours", true, "1 action", "Touch", "/api/spells/meld-into-stone"),
("Conjure Fey", 6, "Up to 1 hour", false, "1 minute", "90 feet", "/api/spells/conjure-fey");