INSERT INTO Spells
    (Index, Name, api_link)
VALUES
    ("cart", "Cart", "/api/equipment/cart"),
    ("case-crossbow-bolt", "Case, crossbow bolt", "/api/equipment/case-crossbow-bolt"),
    ("acid-vial", "Acid (vial)", "/api/equipment/acid-vial"),
    ("blowgun", "Blowgun", "/api/equipment/blowgun"),
    ("cartographers-tools", "Cartographer's tools", "/api/equipment/cartographers-tools"),
    ("barding-padded", "Barding: Padded", "/api/equipment/barding-padded"),
    ("chain-10-feet", "Chain (10 feet)", "/api/equipment/chain-10-feet"),
    ("blanket", "Blanket", "/api/equipment/blanket"),
    ("clothes-costume", "Clothes, costume", "/api/equipment/clothes-costume"),
    ("bottle-glass", "Bottle, glass", "/api/equipment/bottle-glass"),
    ("alchemists-fire-flask", "Alchemist's fire (flask)", "/api/equipment/alchemists-fire-flask"),
    ("barding-plate", "Barding: Plate", "/api/equipment/barding-plate"),
    ("flail", "Flail", "/api/equipment/flail"),
    ("calligraphers-supplies", "Calligrapher's supplies", "/api/equipment/calligraphers-supplies"),
    ("backpack", "Backpack", "/api/equipment/backpack"),
    ("alchemists-supplies", "Alchemist's supplies", "/api/equipment/alchemists-supplies"),
    ("bucket", "Bucket", "/api/equipment/bucket"),
    ("barding-half-plate", "Barding: Half plate", "/api/equipment/barding-half-plate"),
    ("burglars-pack", "Burglar's Pack", "/api/equipment/burglars-pack"),
    ("masons-tools", "Mason's tools", "/api/equipment/masons-tools"),
    ("painters-supplies", "Painter's supplies", "/api/equipment/painters-supplies"),
    ("parchment-one-sheet", "Parchment (one sheet)", "/api/equipment/parchment-one-sheet"),
    ("hammer-sledge", "Hammer, sledge", "/api/equipment/hammer-sledge"),
    ("lock", "Lock", "/api/equipment/lock"),
    ("dulcimer", "Dulcimer", "/api/equipment/dulcimer"),
    ("clothes-travelers", "Clothes, traveler's", "/api/equipment/clothes-travelers"),
    ("dagger", "Dagger", "/api/equipment/dagger"),
    ("brewers-supplies", "Brewer's supplies", "/api/equipment/brewers-supplies"),
    ("camel", "Camel", "/api/equipment/camel"),
    ("crossbow-hand", "Crossbow, hand", "/api/equipment/crossbow-hand"),
    ("halberd", "Halberd", "/api/equipment/halberd"),
    ("oil-flask", "Oil (flask)", "/api/equipment/oil-flask"),
    ("carriage", "Carriage", "/api/equipment/carriage"),
    ("barding-chain-mail", "Barding: Chain mail", "/api/equipment/barding-chain-mail"),
    ("entertainers-pack", "Entertainer's Pack", "/api/equipment/entertainers-pack"),
    ("hide", "Hide", "/api/equipment/hide"),
    ("holy-water-flask", "Holy water (flask)", "/api/equipment/holy-water-flask"),
    ("horn", "Horn", "/api/equipment/horn"),
    ("horse-riding", "Horse, riding", "/api/equipment/horse-riding"),
    ("mule", "Mule", "/api/equipment/mule"),
    ("morningstar", "Morningstar", "/api/equipment/morningstar"),
    ("lantern-hooded", "Lantern, hooded", "/api/equipment/lantern-hooded"),
    ("greatsword", "Greatsword", "/api/equipment/greatsword"),
    ("mess-kit", "Mess Kit", "/api/equipment/mess-kit"),
    ("abacus", "Abacus", "/api/equipment/abacus"),
    ("chariot", "Chariot", "/api/equipment/chariot"),
    ("clothes-fine", "Clothes, fine", "/api/equipment/clothes-fine"),
    ("crossbow-heavy", "Crossbow, heavy", "/api/equipment/crossbow-heavy"),
    ("keelboat", "Keelboat", "/api/equipment/keelboat"),
    ("longbow", "Longbow", "/api/equipment/longbow"),
    ("cooks-utensils", "Cook's utensils", "/api/equipment/cooks-utensils"),
    ("bedroll", "Bedroll", "/api/equipment/bedroll"),
    ("healers-kit", "Healer's Kit", "/api/equipment/healers-kit"),
    ("jug-or-pitcher", "Jug or pitcher", "/api/equipment/jug-or-pitcher"),
    ("hunting-trap", "Hunting trap", "/api/equipment/hunting-trap"),
    ("jewelers-tools", "Jeweler's tools", "/api/equipment/jewelers-tools"),
    ("grappling-hook", "Grappling hook", "/api/equipment/grappling-hook"),
    ("navigators-tools", "Navigator's tools", "/api/equipment/navigators-tools"),
    ("barding-ring-mail", "Barding: Ring mail", "/api/equipment/barding-ring-mail"),
    ("barrel", "Barrel", "/api/equipment/barrel"),
    ("flask-or-tankard", "Flask or tankard", "/api/equipment/flask-or-tankard"),
    ("block-and-tackle", "Block and tackle", "/api/equipment/block-and-tackle"),
    ("ladder-10-foot", "Ladder (10-foot)", "/api/equipment/ladder-10-foot"),
    ("cobblers-tools", "Cobbler's tools", "/api/equipment/cobblers-tools"),
    ("chest", "Chest", "/api/equipment/chest"),
    ("barding-splint", "Barding: Splint", "/api/equipment/barding-splint"),
    ("breastplate", "Breastplate", "/api/equipment/breastplate"),
    ("longship", "Longship", "/api/equipment/longship"),
    ("glassblowers-tools", "Glassblower's tools", "/api/equipment/glassblowers-tools"),
    ("orb", "Orb", "/api/equipment/orb"),
    ("crossbow-light", "Crossbow, light", "/api/equipment/crossbow-light"),
    ("javelin", "Javelin", "/api/equipment/javelin"),
    ("component-pouch", "Component pouch", "/api/equipment/component-pouch"),
    ("clothes-common", "Clothes, common", "/api/equipment/clothes-common"),
    ("half-plate", "Half Plate", "/api/equipment/half-plate"),
    ("blowgun-needle", "Blowgun needle", "/api/equipment/blowgun-needle"),
    ("paper-one-sheet", "Paper (one sheet)", "/api/equipment/paper-one-sheet"),
    ("barding-leather", "Barding: Leather", "/api/equipment/barding-leather"),
    ("lute", "Lute", "/api/equipment/lute"),
    ("lamp", "Lamp", "/api/equipment/lamp"),
    ("ink-pen", "Ink pen", "/api/equipment/ink-pen"),
    ("mirror-steel", "Mirror, steel", "/api/equipment/mirror-steel"),
    ("donkey", "Donkey", "/api/equipment/donkey"),
    ("light-hammer", "Light hammer", "/api/equipment/light-hammer"),
    ("rope-silk-50-feet", "Rope, silk (50 feet)", "/api/equipment/rope-silk-50-feet"),
    ("net", "Net", "/api/equipment/net"),
    ("drum", "Drum", "/api/equipment/drum"),
    ("quiver", "Quiver", "/api/equipment/quiver"),
    ("glaive", "Glaive", "/api/equipment/glaive"),
    ("crossbow-bolt", "Crossbow bolt", "/api/equipment/crossbow-bolt"),
    ("crowbar", "Crowbar", "/api/equipment/crowbar"),
    ("battleaxe", "Battleaxe", "/api/equipment/battleaxe"),
    ("padded", "Padded", "/api/equipment/padded"),
    ("leather", "Leather", "/api/equipment/leather"),
    ("basket", "Basket", "/api/equipment/basket"),
    ("candle", "Candle", "/api/equipment/candle"),
    ("ink-1-ounce-bottle", "Ink (1 ounce bottle)", "/api/equipment/ink-1-ounce-bottle"),
    ("manacles", "Manacles", "/api/equipment/manacles"),
    ("ball-bearings-bag-of-1000", "Ball bearings (bag of 1,000)", "/api/equipment/ball-bearings-bag-of-1000"),
    ("explorers-pack", "Explorer's Pack", "/api/equipment/explorers-pack"),
    ("animal-feed-1-day", "Animal Feed (1 day)", "/api/equipment/animal-feed-1-day"),
    ("galley", "Galley", "/api/equipment/galley"),
    ("playing-card-set", "Playing card set", "/api/equipment/playing-card-set"),
    ("scholars-pack", "Scholar's Pack", "/api/equipment/scholars-pack"),
    ("tinderbox", "Tinderbox", "/api/equipment/tinderbox"),
    ("barding-studded-leather", "Barding: Studded Leather", "/api/equipment/barding-studded-leather"),
    ("wagon", "Wagon", "/api/equipment/wagon"),
    ("maul", "Maul", "/api/equipment/maul"),
    ("hammer", "Hammer", "/api/equipment/hammer"),
    ("horse-draft", "Horse, draft", "/api/equipment/horse-draft"),
    ("handaxe", "Handaxe", "/api/equipment/handaxe"),
    ("perfume-vial", "Perfume (vial)", "/api/equipment/perfume-vial"),
    ("barding-hide", "Barding: Hide", "/api/equipment/barding-hide"),
    ("bagpipes", "Bagpipes", "/api/equipment/bagpipes"),
    ("diplomats-pack", "Diplomat's Pack", "/api/equipment/diplomats-pack"),
    ("emblem", "Emblem", "/api/equipment/emblem"),
    ("arrow", "Arrow", "/api/equipment/arrow"),
    ("leatherworkers-tools", "Leatherworker's tools", "/api/equipment/leatherworkers-tools"),
    ("caltrops", "Caltrops", "/api/equipment/caltrops"),
    ("antitoxin-vial", "Antitoxin (vial)", "/api/equipment/antitoxin-vial"),
    ("club", "Club", "/api/equipment/club"),
    ("case-map-or-scroll", "Case, map or scroll", "/api/equipment/case-map-or-scroll"),
    ("rod", "Rod", "/api/equipment/rod"),
    ("lyre", "Lyre", "/api/equipment/lyre"),
    ("barding-chain-shirt", "Barding: Chain shirt", "/api/equipment/barding-chain-shirt"),
    ("rowboat", "Rowboat", "/api/equipment/rowboat"),
    ("saddlebags", "Saddlebags", "/api/equipment/saddlebags"),
    ("carpenters-tools", "Carpenter's tools", "/api/equipment/carpenters-tools"),
    ("shortbow", "Shortbow", "/api/equipment/shortbow"),
    ("signal-whistle", "Signal whistle", "/api/equipment/signal-whistle"),
    ("dice-set", "Dice set", "/api/equipment/dice-set"),
    ("lance", "Lance", "/api/equipment/lance"),
    ("pan-flute", "Pan flute", "/api/equipment/pan-flute"),
    ("flute", "Flute", "/api/equipment/flute"),
    ("greataxe", "Greataxe", "/api/equipment/greataxe"),
    ("pick-miners", "Pick, miner's", "/api/equipment/pick-miners"),
    ("forgery-kit", "Forgery Kit", "/api/equipment/forgery-kit"),
    ("longsword", "Longsword", "/api/equipment/longsword"),
    ("chain-shirt", "Chain Shirt", "/api/equipment/chain-shirt"),
    ("elephant", "Elephant", "/api/equipment/elephant"),
    ("pony", "Pony", "/api/equipment/pony"),
    ("totem", "Totem", "/api/equipment/totem"),
    ("magnifying-glass", "Magnifying glass", "/api/equipment/magnifying-glass"),
    ("book", "Book", "/api/equipment/book"),
    ("warship", "Warship", "/api/equipment/warship"),
    ("sling-bullet", "Sling bullet", "/api/equipment/sling-bullet"),
    ("amulet", "Amulet", "/api/equipment/amulet"),
    ("spyglass", "Spyglass", "/api/equipment/spyglass"),
    ("pole-10-foot", "Pole (10-foot)", "/api/equipment/pole-10-foot"),
    ("mastiff", "Mastiff", "/api/equipment/mastiff"),
    ("disguise-kit", "Disguise Kit", "/api/equipment/disguise-kit"),
    ("climbers-kit", "Climber's Kit", "/api/equipment/climbers-kit"),
    ("mace", "Mace", "/api/equipment/mace"),
    ("riding", "Riding", "/api/equipment/riding"),
    ("crystal", "Crystal", "/api/equipment/crystal"),
    ("dart", "Dart", "/api/equipment/dart"),
    ("fishing-tackle", "Fishing tackle", "/api/equipment/fishing-tackle"),
    ("chain-mail", "Chain Mail", "/api/equipment/chain-mail"),
    ("greatclub", "Greatclub", "/api/equipment/greatclub"),
    ("lantern-bullseye", "Lantern, bullseye", "/api/equipment/lantern-bullseye"),
    ("herbalism-kit", "Herbalism Kit", "/api/equipment/herbalism-kit"),
    ("chalk-1-piece", "Chalk (1 piece)", "/api/equipment/chalk-1-piece"),
    ("sickle", "Sickle", "/api/equipment/sickle"),
    ("war-pick", "War pick", "/api/equipment/war-pick"),
    ("ring-mail", "Ring Mail", "/api/equipment/ring-mail"),
    ("barding-scale-mail", "Barding: Scale mail", "/api/equipment/barding-scale-mail"),
    ("dungeoneers-pack", "Dungeoneer's Pack", "/api/equipment/dungeoneers-pack"),
    ("barding-breastplate", "Barding: Breastplate", "/api/equipment/barding-breastplate"),
    ("hourglass", "Hourglass", "/api/equipment/hourglass"),
    ("sprig-of-mistletoe", "Sprig of mistletoe", "/api/equipment/sprig-of-mistletoe"),
    ("spear", "Spear", "/api/equipment/spear"),
    ("sealing-wax", "Sealing wax", "/api/equipment/sealing-wax"),
    ("soap", "Soap", "/api/equipment/soap"),
    ("vial", "Vial", "/api/equipment/vial"),
    ("stabling-1-day", "Stabling (1 day)", "/api/equipment/stabling-1-day"),
    ("saddle-pack", "Saddle, Pack", "/api/equipment/saddle-pack"),
    ("saddle-exotic", "Saddle, Exotic", "/api/equipment/saddle-exotic"),
    ("rapier", "Rapier", "/api/equipment/rapier"),
    ("poisoners-kit", "Poisoner's Kit", "/api/equipment/poisoners-kit"),
    ("staff", "Staff", "/api/equipment/staff"),
    ("woodcarvers-tools", "Woodcarver's tools", "/api/equipment/woodcarvers-tools"),
    ("wand", "Wand", "/api/equipment/wand"),
    ("potion-of-healing", "Potion of healing", "/api/equipment/potion-of-healing"),
    ("smiths-tools", "Smith's tools", "/api/equipment/smiths-tools"),
    ("pike", "Pike", "/api/equipment/pike"),
    ("poison-basic-vial", "Poison, basic (vial)", "/api/equipment/poison-basic-vial"),
    ("tinkers-tools", "Tinker's tools", "/api/equipment/tinkers-tools"),
    ("plate", "Plate", "/api/equipment/plate"),
    ("rope-hempen-50-feet", "Rope, hempen (50 feet)", "/api/equipment/rope-hempen-50-feet"),
    ("pot-iron", "Pot, iron", "/api/equipment/pot-iron"),
    ("rations-1-day", "Rations (1 day)", "/api/equipment/rations-1-day"),
    ("warhammer", "Warhammer", "/api/equipment/warhammer"),
    ("weavers-tools", "Weaver's tools", "/api/equipment/weavers-tools"),
    ("trident", "Trident", "/api/equipment/trident"),
    ("bell", "Bell", "/api/equipment/bell"),
    ("studded-leather", "Studded Leather", "/api/equipment/studded-leather"),
    ("robes" , "Robes", "/api/equipment/robes"),
    ("warhorse", "Warhorse", "/api/equipment/warhorse"),
    ("scimitar", "Scimitar", "/api/equipment/scimitar"),
    ("ram-portable", "Ram, portable", "/api/equipment/ram-portable"),
    ("spellbook", "Spellbook", "/api/equipment/spellbook"),
    ("whetstone", "Whetstone", "/api/equipment/whetstone"),
    ("priests-pack", "Priest's Pack", "/api/equipment/priests-pack"),
    ("spike-iron", "Spike, iron", "/api/equipment/spike-iron"),
    ("scale-merchants", "Scale, merchant's", "/api/equipment/scale-merchants"),
    ("thieves-tools", "Thieves' tools", "/api/equipment/thieves-tools"),
    ("torch", "Torch", "/api/equipment/torch"),
    ("potters-tools", "Potter's tools", "/api/equipment/potters-tools"),
    ("pouch", "Pouch", "/api/equipment/pouch"),
    ("quarterstaff", "Quarterstaff", "/api/equipment/quarterstaff"),
    ("sling", "Sling", "/api/equipment/sling"),
    ("saddle-military", "Saddle, Military", "/api/equipment/saddle-military"),
    ("sack", "Sack", "/api/equipment/sack"),
    ("sailing-ship", "Sailing ship", "/api/equipment/sailing-ship"),
    ("viol", "Viol", "/api/equipment/viol"),
    ("shawm", "Shawm", "/api/equipment/shawm"),
    ("whip", "Whip", "/api/equipment/whip"),
    ("wooden-staff", "Wooden staff", "/api/equipment/wooden-staff"),
    ("splint", "Splint", "/api/equipment/splint"),
    ("bit-and-bridle", "Bit and bridle", "/api/equipment/bit-and-bridle"),
    ("shovel", "Shovel", "/api/equipment/shovel"),
    ("yew-wand", "Yew wand", "/api/equipment/yew-wand"),
    ("signet-ring", "Signet ring", "/api/equipment/signet-ring"),
    ("tent-two-person", "Tent, two-person", "/api/equipment/tent-two-person"),
    ("shield", "Shield", "/api/equipment/shield"),
    ("waterskin", "Waterskin", "/api/equipment/waterskin"),
    ("scale-mail", "Scale Mail", "/api/equipment/scale-mail"),
    ("sled", "Sled", "/api/equipment/sled"),
    ("piton", "Piton", "/api/equipment/piton"),
    ("shortsword", "Shortsword", "/api/equipment/shortsword"),
    ("reliquary", "Reliquary", "/api/equipment/reliquary");