INSERT INTO traits
    (name, api_url)
VALUES
('Artificer''s Lore', '/api/traits/artificers-lore'),
('Brave', '/api/traits/brave'),
('Breath Weapon', '/api/traits/breath-weapon'),
('Damage Resistance', '/api/traits/damage-resistance'),
('Darkvision', '/api/traits/darkvision'),
('Draconic Ancestry', '/api/traits/draconic-ancestry'),
('Dwarven Combat Training', '/api/traits/dwarven-combat-training'),
('Dwarven Resilience', '/api/traits/dwarven-resilience'),
('Dwarven Toughness', '/api/traits/dwarven-toughness'),
('Elf Weapon Training', '/api/traits/elf-weapon-training'),
('Extra Language', '/api/traits/extra-language'),
('Fey Ancestry', '/api/traits/fey-ancestry'),
('Gnome Cunning', '/api/traits/gnome-cunning'),
('Halfling Nimbleness', '/api/traits/halfling-nimbleness'),
('Hellish Resistance', '/api/traits/hellish-resistance'),
('High Elf Cantrip', '/api/traits/high-elf-cantrip'),
('Infernal Legacy', '/api/traits/infernal-legacy'),
('Keen Senses', '/api/traits/keen-senses'),
('Lucky', '/api/traits/lucky'),
('Menacing', '/api/traits/menacing'),
('Naturally Stealthy', '/api/traits/naturally-stealthy'),
('Relentless Endurance', '/api/traits/relentless-endurance'),
('Savage Attacks', '/api/traits/savage-attacks'),
('Skill Versatility', '/api/traits/skill-versatility'),
('Stonecunning', '/api/traits/stonecunning'),
('Tinker', '/api/traits/tinker'),
('Trance', '/api/traits/trance');