DROP TABLE IF EXISTS race_traits CASCADE;
CREATE TABLE race_traits (
  id SERIAL PRIMARY KEY NOT NULL,
  race_id INTEGER REFERENCES races(id) ON DELETE CASCADE,
  trait_id INTEGER REFERENCES traits(id) ON DELETE CASCADE
);